/* CRITICAL LOAD — episode data E7-E9 */
window.DATA3 = [

/* ================= E7 COMMISSIONING & DELIVERY ================= */
{
  id: "e7", num: 7, icon: "✅", title: "Commissioning & Delivery",
  tagline: "Levels 1 through 5, integrated systems testing, and who really decides when ready-for-service is ready.",
  walk: [
    "Hall D is chaos with a schedule: ladders, cable lifts, a forest of racks with no servers, and rows of refrigerator-sized resistor banks glowing faintly as fans roar through them. Dee shouts over the noise. “Load banks. Fake servers. We’re making thirty-six megawatts of pretend compute so we can find out what breaks before your client’s real silicon arrives.”",
    "A woman in a hard hat is making notes on a tablet, unhurried in the din. Dee introduces her: “Priya Raman, commissioning agent. Third party. She works for the project, not for me, and definitely not for Marcus.” Priya looks up. “I fail things for a living, counsel. Last week I failed a generator paralleling sequence twice. Dee’s team fixed it. That’s the system working. The thing you need to understand before you paper the delivery terms is simple: until I have pulled the utility breaker at full load and watched this building catch itself, nobody knows if it works. They believe. Belief is not a delivery condition.”"
  ],
  concepts: [
    { term: "Commissioning (Cx) and the commissioning agent", body: "Commissioning is the staged, documented process of proving the facility performs as designed. The <b>commissioning agent (CxA)</b> runs it: scripts the tests, witnesses them, logs failures, and certifies results. The contractual crux is independence: a CxA engaged by and reporting to the project (with customer visibility) versus the operator grading its own homework. Customer rights to review scripts, witness tests, and receive raw results belong in the delivery section." },
    { term: "Levels 1 and 2: factory and arrival", body: "<b>Level 1</b> is factory witness testing: the UPS or generator demonstrated at the manufacturer’s plant before shipping. <b>Level 2</b> is site arrival inspection: did the unit survive the truck. Cheap to do, cheap to skip, and skipped units have a way of revealing shipping damage eight months later, mid-outage." },
    { term: "Level 3: startup", body: "Individual equipment energized and started per manufacturer procedure: does this chiller run, does this UPS rectify. Performed by vendors, witnessed by the CxA. A facility that is “energized” is at Level 3. Marketing decks love the word energized. It means the lights are on, nothing more." },
    { term: "Level 4: functional performance", body: "Each <b>system</b> exercised against its design intent: this UPS lineup carries rated load and transfers correctly, this chiller plant delivers design tonnage, controls sequence as drawn. Still siloed: electrical proven separately from mechanical, system by system. Most of the schedule lives here, and this is where operators want to declare victory." },
    { term: "Level 5: integrated systems testing (IST)", body: "The graduation exam. The whole facility run as one organism at design load (those load banks), then deliberately attacked: pull the utility, kill a UPS, trip a chiller, fail a control processor, all while watching every system catch every other system. The pull-the-plug test. IST at full design load with the CxA certifying results is the only event that proves the building works. It is also weeks of schedule and real diesel and load bank money, which is why it is the thing operators most want to soften, shorten, sample, or skip." },
    { term: "RFS, milestones, and delay remedies", body: "<b>Ready for Service</b> is the contractual moment the facility (or a capacity block) is deliverable: billing starts, the term starts, the ramp clock starts. The customer’s definition: Level 5 IST passed at full design load, CxA certificate delivered, punch list below an agreed materiality threshold. The structure around it: dated milestones (long-lead equipment orders, energization, Cx start), delay liquidated damages per day per MW, often credited against rent, and an outside date with customer termination and cost recovery. Operators counter with “substantial completion” language imported from construction practice, where it means the building is usable despite incomplete items, a concept that maps badly onto a facility whose entire value is proven performance under failure." }
  ],
  warStory: [
    "Priya tells this one herself, without looking up from the tablet. “Facility in Northern Virginia, a few years back. Not my project, I did the autopsy. Schedule pressure, anchor tenant threatening to walk, so the parties agreed to ‘provisional RFS’: Level 4 complete, IST deferred ninety days, to be performed ‘around’ the live load. The tenant’s lawyers papered it with an indemnity. An indemnity, for physics.",
    "You cannot pull the utility breaker on a building full of someone’s production compute, so the deferred IST quietly became a paper exercise: component retests, no integrated failure simulation. Fourteen months later a real utility event hit, and a control sequence that had never been tested end-to-end ordered the chilled water plant to restart in the wrong order. Forty minutes of thermal excursion, eight figures of hardware claims, and a finding that the sequence defect would have been caught by any competent IST in an afternoon. The deferral didn’t defer the test. The grid ran it for them, with live ammunition.”"
  ],
  bites: [
    { where: "RFS definition", what: "Level 5 IST passed at one hundred percent of design load, CxA certificate delivered, punch list below threshold. Resist “substantial completion,” “energized,” or “Level 4 plus operator certificate” as the trigger that starts your rent." },
    { where: "CxA independence and customer rights", what: "Named or jointly approved CxA, customer right to review test scripts in advance, witness all Level 4 and 5 testing, and receive complete raw results, not summaries." },
    { where: "Milestone schedule and delay LDs", what: "Dated milestones per capacity block with per-day liquidated damages, escalating, plus an outside date with termination and recovery of customer’s stranded costs. LDs styled as rent credits are fine, LDs capped at a trivial number are not remedies, they are pricing." },
    { where: "Punch list materiality", what: "Define what open items are compatible with RFS (cosmetic, non-critical-path) versus what blocks it (anything touching the power or cooling chain, life safety, or controls). Otherwise “punch list” becomes a basket for deferred critical work." },
    { where: "Phased delivery interaction", what: "Each ramp block needs its own commissioning scope, including proof that adding block N did not degrade blocks 1 through N-1: integration testing at each phase boundary, not just the first." }
  ],
  trap: {
    clause: "“Ready for Service” means that the applicable Capacity Block has achieved substantial completion, with commissioning through Level 4 complete as certified by Operator’s engineer, subject only to punch list items that do not materially impair Customer’s use of the Premises. Level 5 integrated systems testing shall be completed within ninety days following the RFS Date where commercially practicable.",
    q: "Where is the trap?",
    options: [
      "RFS triggers on Level 4 self-certified by the operator’s own engineer, while the only test that proves the facility (IST) is deferred until after billing starts and softened to “where commercially practicable,” which after live load means never.",
      "Substantial completion is a meaningless term with no construction-law pedigree.",
      "Ninety days is too short a period for Level 5 testing, which requires a year.",
      "Punch list items should never be permitted at RFS under any standard."
    ],
    correct: 0,
    explain: "Three devices in sequence: the certifier (operator’s engineer grading its own homework), the trigger (Level 4, systems proven only in isolation), and the deferral (IST after RFS “where commercially practicable,” which is unperformable once production load is live, exactly Priya’s autopsy). Substantial completion has a real construction pedigree, which is the problem: it imports a usability standard into a deal about proven failure response. Rent starts, and the building has never been tested as a building.",
    fix: "“Ready for Service” means, with respect to each Capacity Block, that (a) Level 5 integrated systems testing has been completed at one hundred percent of design load, including utility failure simulation and concurrent maintainability demonstrations, in accordance with test scripts approved by Customer, (b) the Commissioning Agent has delivered its certificate confirming successful completion, and (c) open punch list items do not include any item affecting the electrical chain, mechanical chain, controls, or life safety. Customer shall have the right to witness all Level 4 and Level 5 testing and to receive complete test results.",
    fixNote: "The certifier changed, the trigger moved to the real test, and the deferral disappeared. Note the punch list carve-out is defined by system, not by “materiality” adjectives."
  },
  spar: {
    setup: "The delivery schedule is slipping. Marcus proposes the compromise from his last three deals.",
    marcus: "Here’s what I can do. We bifurcate RFS: billing commences at Level 4 completion, since at that point every system has individually proven out and your equipment can physically install, and we complete the IST within the first quarter of the term, around your deployment schedule. You get your capacity months earlier, we get the revenue recognition, and the IST still happens. Your client is burning seven figures a month in GPU depreciation on hardware sitting in crates. I’m offering you the keys early. Don’t let testing theater cost Helios a quarter of compute.",
    options: [
      { text: "“Deferred IST around live load isn’t IST, so no. Full Level 5 before a dollar of billing, as drafted.”", grade: 2, feedback: "Substantively correct, and being right matters. But you answered a schedule crisis with a flat no and left his GPU-depreciation point, which is real and your client feels it daily, completely unaddressed. Deal teams remember who solved the schedule problem and who recited the contract at it. There was a structure available that kept your test AND moved his timeline." },
      { text: "“Agreed, provided Ironvale indemnifies Helios for any losses arising from defects that IST would have identified.”", grade: 0, feedback: "An indemnity, for physics. This is verbatim the Northern Virginia structure from Priya’s autopsy: the test becomes unperformable the moment live load lands, the indemnity becomes a litigation about what IST “would have” caught, and your client’s remedy for forty minutes of thermal excursion is a lawsuit instead of a building that works. Priya is staring at you." },
      { text: "“The early-access instinct is right, the billing trigger is wrong, so let’s split those. Phase the IST: run full Level 5 on Hall D’s first capacity block now, before anything ships, and Helios begins staged installation in that proven block while you commission and IST the remaining blocks behind us. Billing per block at each block’s certified Level 5, which is the structure already in the ramp. Your revenue starts weeks earlier on block one, our hardware gets out of crates, and no IST ever has to happen around live load because each block is tested before it carries any.”", grade: 3, feedback: "This is the answer that closes. You used the deal’s own phasing architecture to dissolve a false binary: Marcus framed it as early-billing-with-deferred-test versus late-billing-with-full-test, and you produced early-partial-billing-with-full-test-per-block. His revenue point is served, the GPU crates open, and the unperformable-test trap never arises. Priya signs block certificates instead of autopsies. This is how sophisticated AI deals actually phase delivery." },
      { text: "“If the schedule’s slipping, that’s what the delay LDs are for. We’ll take the liquidated damages and wait for full IST.”", grade: 1, feedback: "Legally coherent and occasionally even right, but read the room: the LDs were sized as rent credits, your client is burning more in idle hardware than the LDs return, and you’ve just told the business team their compute sits in crates on principle. The LD schedule compensates delay, it doesn’t solve it. Marcus will repeat this answer to your client’s CEO, slowly." }
    ],
    counter: "Use the ramp structure against the false binary. Phase the IST per capacity block: full Level 5 on block one before any customer load, staged installation into proven blocks while later blocks commission behind, billing per block on each certified Level 5. The operator’s revenue starts early, the customer’s hardware deploys early, and no test is ever deferred around live load, because the live load only ever lands on tested blocks."
  },
  bank: [
    { q: "From E6: why does a customer fight for a monthly rather than annual SLA measurement window?", options: ["An annual window lets the operator amortize a major outage across eleven clean months, so the same percentage forgives far larger single events", "Monthly windows produce more paperwork, which deters operators", "Annual windows are illegal in most states", "Because credits compound monthly under annual windows"], correct: 0, explain: "Same nines, different accumulation. 99.99% annually absorbs a 52-minute disaster without breach. Monthly math keys remedies and chronic triggers to the actual rhythm of the customer’s exposure." },
    { q: "What does Level 5 integrated systems testing prove that Level 4 cannot?", options: ["That the facility performs as one system under failure: utility pulls, equipment trips, and control sequences, with every system catching every other at design load", "That each individual UPS meets its factory specification", "That the equipment survived shipping from the manufacturer", "That the facility’s lights and controls are energized"], correct: 0, explain: "Level 4 proves systems in isolation. IST attacks the integrated whole at full load, which is where sequencing defects, the kind that order a chiller plant to restart in the wrong order, actually live. It is the only event that proves the building, and the only honest RFS trigger." },
    { q: "Why is “IST to be completed within 90 days after RFS” effectively a waiver of IST?", options: ["Once production load is live you cannot pull the utility breaker or simulate failures against it, so the deferred test degrades into component retests that prove nothing integrated", "Because 90 days is insufficient time to schedule load banks", "Because commissioning agents refuse engagements after RFS", "It isn’t, since a deferred test is contractually equivalent to a completed one"], correct: 0, explain: "Failure simulation against someone’s production compute is not a thing anyone will authorize. Deferral converts the pull-the-plug test into paperwork, and the first real grid event becomes the IST, with live ammunition. Phase the testing per block instead." }
  ],
  card: {
    term: "Integrated Systems Test (Level 5)",
    physical: "The full-facility exam at design load using load banks, in which utility power is deliberately pulled and equipment deliberately failed to prove every system catches every other system, end to end.",
    contractual: "The only honest Ready for Service trigger, certified by an independent commissioning agent with customer witness rights, because any structure that starts billing before it, or defers it past live load, starts the term on belief instead of proof."
  }
},

/* ================= E8 POWER ECONOMICS ================= */
{
  id: "e8", num: 8, icon: "💰", title: "Power Economics",
  tagline: "Take-or-pay, demand charges, and how a PUE decimal quietly moves seven figures a year.",
  walk: [
    "Back in the conference room, Dee slides a utility bill across the table, eleven pages, and taps the last line. “Four point one million dollars. One month, this campus. Now I’ll tell you the number that should actually scare you: about a third of that bill isn’t energy. It’s demand charges, capacity reservations, riders, and pass-through mechanics, and every one of those line items gets reallocated between Ironvale and its customers by contract language, not by the utility.”",
    "She pulls up a dashboard: a single large number, 1.21, updating every few seconds. “That’s the campus PUE, live. Power usage effectiveness. Every watt your client’s servers drink, the building drinks more on top, for cooling and conversion losses, and the contract decides whether Helios pays for the building’s actual thirst or a number Marcus made up in 2024. One decimal place in that mechanism, across 36 megawatts and fifteen years, is more money than every legal fee on this deal combined. Today we do math.”"
  ],
  concepts: [
    { term: "Metered vs allocated power", body: "<b>Metered</b>: the customer pays for actual kWh consumed, measured at dedicated meters, at a defined rate or pass-through. <b>Allocated</b> (or capacity-based): the customer pays for its reserved block whether used or not. Large deals blend both: a capacity charge for the reservation plus metered energy. The audit question is always where the meters sit (E1’s measurement-point lesson, now with invoices attached)." },
    { term: "Take-or-pay and minimum commitments", body: "The customer pays for contracted capacity from each block’s billing start, at full freight or a stated minimum percentage, regardless of utilization. Operators need it: they bought generators and chillers against your reservation. Customers manage it through the ramp (don’t take blocks early), through minimum percentages that step up, and through rights to resell or sublicense unused capacity. The silent version is worse: a high “infrastructure charge” per reserved kW that functions as take-or-pay without the label." },
    { term: "Demand charges and capacity reservation", body: "Utilities bill big customers two ways at once: <b>energy</b> (per kWh consumed) and <b>demand</b> (per kW of peak draw, often the highest 15-minute interval in the month, sometimes ratcheted for months afterward). A single load spike sets the demand charge for the period. Contract question: how are demand charges allocated among customers sharing a feed, and does Helios pay for a peak another tenant caused? Dedicated metering and proportionate-cause allocation language are the defenses." },
    { term: "PUE", body: "Power usage effectiveness: total facility power divided by IT power. A PUE of 1.3 means every IT kWh costs 1.3 kWh at the fence. Modern hyperscale runs 1.1 to 1.3, legacy colo 1.5 to 1.8+. PUE moves with climate, season, load level, and operational discipline, which is why <b>who bears PUE risk</b> is a negotiation: it is the operator’s efficiency, paid for, under most structures, by the customer." },
    { term: "PUE pass-through math", body: "The standard mechanism: Customer pays IT kWh × PUE factor × utility rate. The fight is what “PUE factor” means. <b>Fixed</b> PUE (say 1.5): operator keeps the upside if it runs at 1.25, customer overpays forever. <b>Actual metered</b> PUE: honest, but customer eats operational sloppiness and seasonal swings. The well-advised structure: actual metered PUE, <b>capped</b> at a guaranteed design PUE, reconciled annually. Customer gets efficiency truth plus a ceiling, operator keeps an incentive to run tight. At 36MW, the difference between paying 1.5 fixed and 1.25 actual is on the order of $6M a year at common industrial rates." },
    { term: "Audit rights and invoice transparency", body: "The pass-through is only as honest as its paper trail: customer rights to the underlying utility invoices, meter data at stated granularity, the PUE calculation inputs, and periodic audit with a true-up. Operators offer summaries. Summaries are where rounding lives. At this scale, meter-level data feeds and an annual independent audit right are standard asks, with discrepancies above a threshold triggering fee-shifted audit costs." }
  ],
  warStory: [
    "“Enterprise customer, ten megawatts, signed a 1.55 fixed PUE pass-through in 2016 because the number sounded technical and the lawyers had bigger fights. The facility was decent and got better: new chillers in 2019, containment retrofit in 2020, actual PUE drifted down to 1.28. Nobody recalculated anything, because nothing required anyone to. Run the arithmetic: ten megawatts of IT load, the spread between 1.55 and 1.28, roughly twenty-four million kWh a year of phantom electricity, billed at pass-through rates, for years.",
    "The customer found it during a renewal diligence exercise when a new energy consultant asked a one-line question: ‘has anyone ever seen the utility invoices?’ Nobody had. No audit right in the contract, no invoice delivery obligation, no true-up. Twenty-plus million dollars of margin, fully legal, fully enforceable, built out of one fixed decimal and one missing audit clause. The operator’s CFO reportedly called that contract ‘the gift.’ Don’t draft gifts.”"
  ],
  bites: [
    { where: "Power charge structure", what: "Separate the capacity charge (the reservation) from metered energy (the consumption), each with its own mechanics. Blended “power fees” hide the take-or-pay inside the rate and make audits meaningless." },
    { where: "PUE mechanism", what: "Actual metered PUE, capped at a guaranteed design PUE, annual reconciliation and true-up. Define the formula’s inputs: which meters, which loads count as IT versus facility, how mixed-use campus overhead is allocated." },
    { where: "Demand charge allocation", what: "Dedicated utility metering where feasible. On shared feeds, allocation by causation (whose draw set the peak) or by proportionate consumption, stated in a formula, not “equitably allocated by Operator.”" },
    { where: "Take-or-pay calibration", what: "Minimums that follow the ramp, step-up percentages, rights to defer a block with notice, and resale or transfer rights for committed-but-unused capacity within the campus." },
    { where: "Audit and transparency", what: "Utility invoices delivered with each statement, meter data at defined granularity, annual independent audit right, true-up both directions, audit costs shifted above a discrepancy threshold." },
    { where: "Renewable adders and riders", what: "If Helios has clean-energy commitments: who procures RECs or green tariffs, at what adder, and whether the operator’s utility riders (fuel surcharges, grid fees) pass through at cost with documentation or arrive pre-marinated in margin." }
  ],
  trap: {
    clause: "Customer shall pay monthly Power Charges equal to Customer’s metered IT consumption in kWh multiplied by the PUE Factor multiplied by the blended utility rate, as each is reasonably determined by Operator. The PUE Factor is 1.50. Operator’s determination of Power Charges shall be conclusive absent manifest error.",
    q: "Where is the trap?",
    options: [
      "A fixed 1.50 PUE in a facility likely running far lower, a “blended rate” the operator constructs, and a conclusiveness clause standing in for audit rights: the gift contract, in one paragraph.",
      "PUE cannot exceed 1.0 by definition, so the factor is facially impossible.",
      "The formula incorrectly multiplies rather than divides by the PUE Factor.",
      "Power charges may not lawfully be passed through to colocation customers."
    ],
    correct: 0,
    explain: "Three devices: the fixed 1.50 books the efficiency spread to the operator forever (the war story, verbatim). The “blended utility rate, reasonably determined” lets the operator construct a rate from inputs you never see, demand charges and riders included, allocated however flatters the margin. And “conclusive absent manifest error” is an audit-rights deletion wearing a standard-of-review costume. (PUE is total over IT power, so it always exceeds 1.0, and multiplying is the correct arithmetic. The formula is fine. The inputs are the trap.)",
    fix: "Customer shall pay monthly Power Charges equal to Customer’s metered IT consumption in kWh multiplied by the Actual PUE multiplied by the actual utility rate paid by Operator, passed through at cost. “Actual PUE” means the Facility’s trailing twelve month measured PUE, calculated as set forth in Exhibit G, and shall not exceed the Guaranteed PUE of 1.30. Operator shall deliver the underlying utility invoices and meter data with each statement. Customer may audit Power Charges annually through an independent auditor, with discrepancies exceeding two percent reimbursed with interest and audit costs.",
    fixNote: "Actual, capped, documented, auditable. The Guaranteed PUE number itself is negotiable. The structure is not."
  },
  spar: {
    setup: "You’ve proposed actual metered PUE capped at 1.30. Marcus produces a spreadsheet with the weary confidence of a man who has shown it before.",
    marcus: "Fixed PUE is a feature, not a con. Your client gets budget certainty: one number, fifteen years, financeable. Actual PUE means Helios’s power bill swings with the weather, with our other tenants’ load profiles, with maintenance cycles, things you have zero control over. Your CFO will hate it. And a 1.30 cap on a building this dense? Liquid loads change the whole PUE math. Nobody guarantees 1.30 on a hybrid air-liquid facility, the engineering just doesn’t support it. 1.50 fixed protects everyone.",
    options: [
      { text: "“Then make it 1.40 fixed instead of 1.50. We’ll meet you in the middle.”", grade: 1, feedback: "You haggled the decimal and conceded the structure, which was the entire game. A fixed 1.40 in a facility that will run 1.20 to 1.25 (dense liquid-cooled loads run efficient, not inefficient) still books millions a year of phantom electricity to the operator, and there is still no invoice, no meter data, and no audit behind the number. The war-story customer also thought their fixed number sounded reasonable." },
      { text: "“Budget certainty that systematically overcharges isn’t certainty, it’s a fixed-price gift, and my CFO can model weather. But let’s take your arguments at face value, because each one prices. If actual PUE is volatile, the cap is what tames it: Helios’s downside is bounded at the Guaranteed PUE while honest months bill honest. And if, as you say, the engineering can’t support 1.30, then show us: the cap should be set from your own design-day PUE model, the one your engineers ran to size this plant, plus a reasonable margin. Give us that model and we’ll set the Guaranteed PUE off it. If you won’t show the model, the 1.50 wasn’t engineering either.”", grade: 3, feedback: "Complete. You exposed the asymmetry at the heart of “certainty” (the customer bears all of it, the operator none), showed the cap already answers the volatility objection, and then converted his engineering claim into a disclosure obligation: set the guarantee off the operator’s own design model. Either the model exists and prices the cap honestly, or the resistance reveals itself as margin defense. Dense liquid loads, incidentally, tend to improve PUE, and Marcus knows you might know that." },
      { text: "“Fine, fixed PUE, but it steps down 0.05 every three years to track efficiency improvements.”", grade: 2, feedback: "Genuinely cleverer than splitting the decimal: a declining fixed number captures some of the efficiency curve and finance teams do like it. But it’s still untethered from the building’s actual performance, still requires no invoices, meters, or audit, and if actual PUE drops faster than the staircase (it usually does after retrofits), the spread is still the operator’s. A workable fallback position. Not the opening one." },
      { text: "“We’ll accept 1.50 fixed if Ironvale reps that the facility’s actual PUE will not be lower than 1.45.”", grade: 0, feedback: "Read what you proposed: a representation that the building will stay inefficient, which the operator cannot control, would breach by improving, and would never sign. Marcus now knows the math behind the mechanism hasn’t fully landed on your side of the table, and the rest of the economics negotiation just got harder." }
    ],
    counter: "The cap already answers the volatility argument: actual metered PUE with a Guaranteed PUE ceiling gives the customer bounded downside and honest billing, while fixed PUE gives the customer all the downside dressed as certainty. Then convert the engineering objection into disclosure: the operator sized this plant with a design-day PUE model, so set the Guaranteed PUE from that model plus margin. Refusing to show the model concedes the number was margin, not engineering."
  },
  bank: [
    { q: "From E1: why does the contract’s power measurement point matter to the monthly bill, not just the capacity grant?", options: ["Meters upstream of the UPS and transformers capture electrical losses and potentially mechanical load as “customer consumption,” inflating every kWh billed", "Upstream meters are read less frequently", "The measurement point determines the utility’s tariff class", "It doesn’t, since consumption is identical wherever measured"], correct: 0, explain: "E1’s lesson, monetized: between the substation and the PDU sit conversion losses and the cooling plant. Billing meters belong at the same defined point as the capacity definition, or the PUE mechanism double-counts the overhead it was supposed to allocate." },
    { q: "A facility bills IT kWh × fixed PUE of 1.50 while actually running at 1.25. On 36MW of IT load, what is happening?", options: ["Roughly a quarter more electricity than the building uses on the customer’s behalf is being billed, a multi-million dollar annual spread booked as operator margin", "Nothing improper, since fixed factors are self-correcting", "The customer is underpaying, because actual PUE includes IT load twice", "The utility, not the operator, keeps the difference"], correct: 0, explain: "The customer pays for 1.50 units at the fence per IT unit while the building draws 1.25: phantom kWh at pass-through rates, compounding annually, forever, with no audit trail unless the contract built one. Actual metered PUE, capped at a guaranteed number, with invoices and audit rights, is the defense." },
    { q: "What is a demand charge and why does sharing a utility feed complicate it?", options: ["A charge keyed to peak kW draw (often one 15-minute interval, sometimes ratcheted), so on a shared feed one tenant’s spike can set a peak the allocation formula spreads to everyone", "A fee for requesting service ahead of construction", "The minimum monthly energy charge under take-or-pay", "A penalty for exceeding contracted ramp milestones"], correct: 0, explain: "Demand charges bill the peak, not the average, and ratchets can echo one spike for months. On shared infrastructure the contract’s allocation formula, by causation or proportionate use, decides whether Helios pays for another tenant’s bad afternoon." }
  ],
  card: {
    term: "PUE (Power Usage Effectiveness)",
    physical: "Total facility power divided by IT power: a PUE of 1.3 means the building draws 1.3 kWh at the fence for every kWh the servers use, with the overhead going to cooling and conversion losses, moving with climate, load, and operational discipline.",
    contractual: "The multiplier in the power pass-through, where a fixed number set above actual performance bills phantom electricity for the life of the term, and the defense is actual metered PUE capped at a guaranteed ceiling with invoice delivery and audit rights."
  }
},

/* ================= E9 OPERATIONS ================= */
{
  id: "e9", num: 9, icon: "🔧", title: "Operations",
  tagline: "Maintenance windows, MOPs, the human error problem, and audit rights that see inside the building.",
  walk: [
    "Dee’s office is a window onto the operations center: a wall of dashboards, two technicians on shift, a whiteboard with this week’s work schedule in four colors. She hands you a three-ring binder, heavy as a deposition. “One maintenance procedure. Sixty pages. Annual UPS service, Gallery A. Every breaker position, every verification step, every phone number to call if step 41 reads wrong, and a back-out path from every stage. We call it a MOP, method of procedure.”",
    "She drops it on the desk. “Here’s the number that should organize your whole ops section: somewhere around two-thirds to three-quarters of data center outages trace to human error, depending whose survey you read. Not equipment. People. Every component in this building exists twice, but a technician with the wrong drawing exists once and touches everything. You can’t draft the human race out of the building. What you can draft is the system that catches humans before physics does: windows, notice, procedures, staffing, and the right to come look. That’s today.”"
  ],
  concepts: [
    { term: "Maintenance windows", body: "Pre-agreed periods when planned work may occur, with defined advance notice (commonly 5 to 10 business days for routine, longer for major), duration limits, and frequency caps. The counterpart: customer <b>freeze periods</b>, windows the customer designates (quarter-end, a training run, a product launch) when non-emergency work stops. In a concurrently maintainable facility, maintenance shouldn’t drop load anyway, so the windows govern <b>risk posture</b>, not expected outages: during the window you may be one failure from impact instead of two." },
    { term: "MOPs, SOPs, and EOPs", body: "<b>SOP</b>: standard operating procedure, the routine playbook. <b>MOP</b>: method of procedure, the scripted, step-by-step, peer-reviewed plan for a specific maintenance task, with verification points and back-out paths. <b>EOP</b>: emergency operating procedure, the drilled response to failures. The lawyer’s questions: do they exist for all critical work, who reviews them, are they rehearsed, and does the customer get visibility (summaries or review rights) for work touching its critical path. An operator that resists showing any MOP governance is telling you about its MOP governance." },
    { term: "Human error and operational discipline", body: "The industry’s consistent finding (Uptime Institute surveys, year after year): the majority of outages have a human cause somewhere in the chain, wrong breaker, stale drawing, skipped verification, untrained contractor. The contractible proxies for discipline: minimum staffing levels (24/7 qualified coverage, stated headcount), training and certification requirements, drill frequency, change management process, and incident reporting with root cause analysis delivered to the customer on a deadline." },
    { term: "Access and security operations", body: "Customer access rights to its premises 24/7/365 without notice, badging procedures and turnaround times for adds and removals, escorted versus unescorted zones, visitor handling, and hands-and-eyes service terms (response time, rates). Plus the inverse: who on the operator side can enter <b>your</b> cage or hall, under what logging. In an AI deployment the hardware in the racks can be worth more than the building, and physical access governance is part of the security model your client’s own customers will audit." },
    { term: "SOC 2, ISO 27001, and audit rights", body: "<b>SOC 2 Type II</b>: an auditor’s report that the operator’s controls (security, availability) were designed and <b>operated effectively over a period</b>, typically twelve months. Type I covers design at a point in time only. <b>ISO 27001</b>: certification of an information security management system. Contract substance: annual delivery of the reports, an obligation to maintain certifications through the term, remediation duties for noted exceptions, and customer audit rights (frequency, scope, notice) including the right to pass through audits your client’s own regulators or customers require. The report names matter less than the delivery-and-remediation machinery." },
    { term: "Incident reporting and RCA", body: "When something happens: immediate notification (commonly within 15 to 60 minutes for events affecting the customer), a preliminary report within days, and a full <b>root cause analysis</b> within a stated period (often 10 to 30 days) with corrective actions and implementation dates. The RCA obligation is how one customer’s incident becomes every customer’s fix, and how your client learns whether Tuesday’s blip was a squirrel or a systemic control defect. Without a deadline and a deliverable, “we’re investigating” lasts forever." }
  ],
  warStory: [
    "“I’ll tell you my own. Years ago, different company, I was the VP who signed the MOP. Annual switchgear maintenance, contractor crew, our staff supervising. Step 14 said open breaker 52-B2. The contractor’s field copy of the one-line diagram was one revision old, from before a bus retrofit, and on his drawing 52-B2 fed a section that was supposed to be already isolated. On the as-built, it fed the live side. Our supervisor was at the far end of the gallery signing a delivery. The contractor opened the breaker his drawing said. Dropped half a data hall, three hundred milliseconds before anyone could inhale.",
    "Postmortem found four failures, every one human: a stale drawing in the field package, a verification step initialed but not performed, a supervisor in two places, a change-management process that had updated the master drawing but not the contractor packet. The equipment was flawless. We built better gates after that, mandatory field verification, two-person rule on every breaker, drawing control with revision receipts. The point for your contract: those gates are exactly the things you can require, staff, verify, and audit. You will never draft away the stale drawing. You draft the four chances to catch it.”"
  ],
  bites: [
    { where: "Maintenance windows and freeze periods", what: "Defined windows, notice periods, frequency and duration caps, customer freeze rights for designated critical periods, and a covenant that planned work never reduces the facility below concurrent maintainability (tying back to E2)." },
    { where: "Operational standards covenant", what: "Staffing minimums (24/7 qualified coverage), training and certification, MOP governance for critical-path work with customer review rights, drill and exercise frequency, change management. The proxies for discipline, made enforceable." },
    { where: "SLA interaction", what: "Maintenance only excludes downtime when performed inside the windows, with notice, per an approved MOP. Work outside that machinery is just an outage. This single linkage makes the whole ops section bite." },
    { where: "Incident reporting and RCA", what: "Notification deadlines in minutes, preliminary report in days, full RCA with corrective actions in a stated period, for any event affecting or reasonably likely to affect Customer’s load." },
    { where: "Access and security", what: "24/7 customer access without notice, badge turnaround times, logging of any operator entry to Customer areas, and hands-and-eyes terms with response times." },
    { where: "Compliance and audit", what: "Maintain SOC 2 Type II and ISO 27001 through the term, deliver reports annually, remediate exceptions, customer and regulator audit rights with defined frequency and scope." }
  ],
  trap: {
    clause: "Operator may perform maintenance to the Facility upon commercially reasonable notice to Customer. Downtime attributable to maintenance activities shall be excluded from Availability calculations. Operator maintains industry standard operational procedures and shall make summaries available to Customer upon reasonable request.",
    q: "Where is the trap?",
    options: [
      "Unbounded maintenance on vague notice, with ALL maintenance downtime excluded from the SLA, so the operator’s riskiest activity, planned work, carries zero SLA consequence however it is performed.",
      "Operators may not lawfully perform maintenance on systems serving an occupied premises.",
      "“Industry standard” is a defined term and therefore enforceable as written.",
      "The clause should also exclude emergency maintenance, which it accidentally omits."
    ],
    correct: 0,
    explain: "The killer is the middle sentence: maintenance downtime excluded from Availability, full stop. Combined with “commercially reasonable notice” (undefined) and procedures available as “summaries” on “reasonable request” (unenforceable courtesy), the operator’s leading cause of outages, human-performed planned work, is contractually consequence-free. Recall the math: most outages trace to human error, and most human error happens during planned work. This clause excludes precisely the risk the ops section exists to govern.",
    fix: "Operator may perform planned maintenance only within the maintenance windows and upon the notice periods set forth in Exhibit H, pursuant to a method of procedure meeting the requirements of Exhibit H, and Customer may designate up to four freeze periods per year during which non-emergency work shall not be performed. Downtime is excluded from Availability calculations only if attributable to planned maintenance performed in compliance with this Section. Operator shall maintain the staffing, training, and change management standards set forth in Exhibit H and shall deliver root cause analyses for any incident affecting Customer’s load within twenty days.",
    fixNote: "One linkage does the work: the SLA exclusion applies only to compliant maintenance. Sloppy work is just an outage, with remedies."
  },
  spar: {
    setup: "You’ve asked for MOP review rights and staffing minimums. Marcus has clearly had this fight before.",
    marcus: "I have forty customers in this building. If each of them gets approval rights over my maintenance procedures and headcount, I don’t have an operations program, I have forty operations programs, and they conflict. My ops team can’t run a facility by committee. You get the SLA, you get the credits, and how I deliver them is my business. That’s what “operator” means. No customer audits my MOPs, and no customer staffs my shifts.",
    options: [
      { text: "“Forty customers is your scaling problem, not our risk tolerance. Helios is the anchor tenant and we expect anchor terms.”", grade: 1, feedback: "Anchor leverage is real, but you asserted status instead of solving his actual objection, which was operational coherence, and it’s a fair objection: forty approval rights genuinely would be chaos. He’ll now offer you a slightly shinier version of the same summaries clause as an “anchor accommodation,” and you’ve given him the vocabulary to do it." },
      { text: "“Nobody asked to run your shifts, so let’s draft what we actually asked for. Not approval, verification. You commit in the exhibit to your own program: staffing minimums, MOP governance, two-person rule on critical-path work, drill frequency, the gates any good operator already runs. We get review of MOPs for work touching our critical path, on notice, no approval right. And the SLA linkage does the governing for us: maintenance only earns its exclusion when performed per that program. Run your building however you like. When work outside the program drops our load, it’s an outage with remedies, not an excluded event. Forty customers can share that structure, because it’s your program, enforced, not forty programs, negotiated.”", grade: 3, feedback: "This dissolves his entire speech. You conceded command (no approval rights, no committee) while taking what matters: the operator’s own standards made contractual, visibility without veto, and the compliance-gated SLA exclusion that converts discipline from a courtesy into a priced term. His forty-customers argument now works for you, since one enforceable program scales where forty veto rights don’t. This is the structure sophisticated deals land on." },
      { text: "“Then give us a dedicated ops team for our halls, walled off from the rest of the building, and run them by your program.”", grade: 2, feedback: "Dedicated staffing is a real structure in very large deployments and at 36MW it’s not absurd to raise. But it’s expensive (you’ll pay for it in the rate), it doesn’t actually answer the governance question (a dedicated team can still work from stale drawings), and it abandoned the cheap, powerful tool already on the table: the compliance-gated SLA exclusion. Big ask, modest protection." },
      { text: "“Fine. We’ll rely on the SLA and credits as you say, but the credit cap triples for outages caused by operator maintenance activity.”", grade: 0, feedback: "You accepted his entire frame, ops as a black box, credits as the only interface, then tripled a number that was never the protection. Recall E6: credits are a deductible, capped and sole-remedy. Tripling a deductible against the leading cause of outages, while waiving all visibility into the activity that causes them, prices the risk without governing it. Marcus will sign before the ink dries on his smile." }
    ],
    counter: "Trade command for verification. No approval rights and no committee: the operator commits to its own operational program in an exhibit (staffing minimums, MOP governance, two-person rule, drills, change management), the customer gets review of critical-path MOPs without veto, and the SLA exclusion for maintenance applies only to work performed in compliance with that program. One enforceable program scales across forty customers precisely because it isn’t forty veto rights."
  },
  bank: [
    { q: "From E7: why must each capacity block in a phased delivery get its own commissioning scope, not just the first?", options: ["Adding block N can degrade blocks 1 through N-1, so each phase boundary needs integration testing proving the live blocks still perform", "Because commissioning certificates expire after ninety days", "Because load banks can only be rented once", "It needn’t, since the first block’s IST covers the facility design"], correct: 0, explain: "Energizing and integrating new lineups changes the system the earlier blocks live in. Phase-boundary integration testing, with billing per block on certified completion, is how the ramp stays honest end to end." },
    { q: "What does the industry’s human-error finding imply for the operations section of the contract?", options: ["Since most outages trace to people performing planned work, the contract should make the SLA maintenance exclusion conditional on compliance with defined procedures, staffing, and notice", "That equipment redundancy should be increased to compensate for staff", "That outages caused by humans are legally force majeure", "That the customer should perform its own facility maintenance"], correct: 0, explain: "The leading outage cause is the one thing blanket maintenance exclusions place beyond the SLA. Gating the exclusion on compliance (windows, notice, MOPs, staffing) converts operational discipline into an enforceable, priced term." },
    { q: "What does a SOC 2 Type II report provide that a Type I does not?", options: ["Evidence that controls operated effectively over a period (typically twelve months), not merely that they were suitably designed at a point in time", "Certification of the facility’s electrical redundancy topology", "A government-issued license to operate data centers", "Coverage of physical security only, excluding availability"], correct: 0, explain: "Type I is a design snapshot, Type II is operation over time, which is what an availability-dependent customer actually needs. The contract machinery matters as much as the acronym: annual delivery, certification maintenance, exception remediation, and pass-through audit rights." }
  ],
  card: {
    term: "MOP (Method of Procedure)",
    physical: "The scripted, peer-reviewed, step-by-step plan for a specific piece of critical facility work, with verification checkpoints and back-out paths at every stage, existing because most outages are caused by humans performing planned work.",
    contractual: "The hinge of the operations section: maintenance should earn its SLA exclusion only when performed under a compliant MOP within noticed windows, so that procedural discipline is a priced contractual condition rather than an operator courtesy."
  }
}
];
