/* CRITICAL LOAD — episode data E4-E6 */
window.DATA2 = [

/* ================= E4 DENSITY & SPACE ================= */
{
  id: "e4", num: 4, icon: "📐", title: "Density & Space",
  tagline: "White space vs gray space, kW per rack, floor loading, and ramp schedules that bill for ghosts.",
  walk: [
    "Dee unrolls a floor plan across a folding table in an empty data hall, your footsteps still echoing off bare concrete. “This is Hall C, your client’s future home. Right now it’s the most honest room in the building, because nothing in here can be misdescribed yet. Once the cages go in, every square foot acquires three different names and two different prices.”",
    "She taps the plan. “Lawyers love square feet because leases are about square feet. Wrong instinct here. Your client is not buying floor, they’re buying the right to put heat into rooms and power into silicon. The floor is just where it happens to sit. Deals that get papered in square feet when they should be papered in kilowatts produce the saddest creature in this industry: stranded capacity. Let me show you the vocabulary before Marcus does.”"
  ],
  concepts: [
    { term: "White space vs gray space", body: "<b>White space</b> is the raised-floor (or slab) area where IT equipment lives: the customer-facing product. <b>Gray space</b> is everything that supports it: electrical galleries, mechanical plant, battery rooms, corridors. A facility’s marketing square footage often blends both. Your premises definition should be white space, with rights (not rent) covering the gray space that serves it." },
    { term: "Rack, cabinet, cage, suite, hall", body: "The granularity ladder. A <b>rack</b> is the 19-inch frame, a <b>cabinet</b> is the enclosed rack (terms get used interchangeably, define one). A <b>cage</b> is a fenced area holding multiple cabinets. A <b>suite</b> or private <b>hall</b> is a dedicated room. Granularity determines security model, expansion rights, and what “your space” legally is. At 36MW Helios takes dedicated halls, but expansion options may be cage-level." },
    { term: "kW per rack (design density)", body: "The facility’s power and cooling are engineered around a design density, classically 5 to 10kW per rack, modern cloud 15 to 30, AI 80 to 130+. Three different numbers hide inside “density”: the <b>average</b> across the hall, the <b>peak</b> any single rack may draw, and the <b>contracted</b> total. Operators commit to averages and police peaks. Your client deploys in dense rows, which is where averages betray you." },
    { term: "Floor loading", body: "Structural capacity in pounds per square foot. Legacy raised floors run 150 to 250 psf. A loaded AI rack with liquid cooling can exceed 4,000 pounds on a footprint of about six square feet, far past legacy numbers even with load spreaders. On upper floors or old buildings this is a genuine no-go check, not boilerplate. The structural exhibit should state point load and distributed load capacity, verified by the structural engineer of record." },
    { term: "Ramp schedule", body: "Big deals deliver and bill capacity in tranches: 6MW at RFS, then 6MW per quarter, say. The ramp is where two clocks live: the operator’s <b>delivery</b> obligation (when each block must be ready) and the customer’s <b>payment</b> obligation (when billing starts on each block, often regardless of actual use, a take-or-pay structure covered in E8). The trap is asymmetry: hard dates on your payments, soft dates on their delivery." },
    { term: "Stranded capacity", body: "When one resource runs out before the others: all the floor used but half the power, or all the power sold but empty floor. Whoever bears stranding risk loses real money. If you contract space with a density cap, the operator strands <b>your</b> power. If you contract power with generous space, you can strand <b>theirs</b>. This single allocation explains half the fights in the density exhibit." }
  ],
  warStory: [
    "“Customer signed for 10,000 square feet at ‘up to 8kW per rack average.’ Their architecture put twelve 15kW racks in a row with empty space between rows, dead average of 7.2kW. Comfortably under, right? Operator red-tagged the install. The clause said average density per row, in a definitions cross-reference nobody read, because the cooling units served row pairs and couldn’t handle a hot row regardless of the hall average.",
    "Eighteen months of lawyers arguing about what ‘average’ modified, while the customer paid rent on a hall they couldn’t fill. The operator wasn’t even wrong about the physics: the CRAHs really couldn’t cool that row. Everyone papered an average, and physics works in peaks. The lesson isn’t that someone was sneaky. It’s that density has a geometry, and your exhibit has to draw it, not summarize it.”"
  ],
  bites: [
    { where: "Premises definition", what: "White space identified on a plan, with appurtenant rights to gray space, pathways, and risers. If the premises blends gray space, you are paying rent on their chillers." },
    { where: "Density schedule", what: "Total kW, per-hall kW, per-row or per-cage peaks, and the cooling method per density band. Specify what happens if Helios wants to re-balance the layout later: re-stamping rights with defined engineering review, not operator discretion." },
    { where: "Floor loading & structural exhibit", what: "Stated psf (distributed and point load) certified by the structural engineer, plus rigging paths, freight elevator capacity, and slab-to-slab heights for liquid cooling overhead." },
    { where: "Ramp schedule symmetry", what: "Each capacity block needs a delivery date with delay remedies mirroring the billing date. If billing starts on “Availability” as certified by the operator, the operator controls your rent commencement." },
    { where: "Expansion and right of first refusal", what: "AI deployments grow. Expansion options on adjacent halls, with pre-agreed pricing formulas and density terms, are worth more than rent savings. Without them, your own success becomes the operator’s leverage at renewal." }
  ],
  trap: {
    clause: "Customer may install equipment in the Premises at a density not to exceed 8kW per rack on average across the Premises, subject to Operator approval of Customer’s installation plan, which approval shall not be unreasonably withheld. Billing for each Capacity Block shall commence upon Operator’s notice that such Capacity Block is Available.",
    q: "Where is the trap?",
    options: [
      "An average density cap that ignores layout geometry, an approval right over every install, and billing that starts on the operator’s own self-certified notice.",
      "8kW per rack is physically impossible for any modern server, making the clause a nullity.",
      "“Not unreasonably withheld” is unenforceable in commercial contracts.",
      "Billing should commence on signature, not on availability, to give the operator certainty."
    ],
    correct: 0,
    explain: "Three devices. The average cap sounds permissive but physics polices peaks, so the operator can deny any realistic dense layout while the average reads fine, and the approval right makes that denial procedural. And “Available” on operator notice means the operator starts your rent clock by sending a letter, with no commissioning standard or customer verification behind it. (8kW racks are very possible, just not for AI training gear.)",
    fix: "Customer may install equipment at densities up to the values set forth in the Density Schedule in Exhibit D, which shall specify permitted kW per rack, per row, and per hall and the supported cooling method for each density band. Operator shall review installation plans solely for conformity with the Density Schedule and shall approve or specify nonconformities within ten business days. Billing for each Capacity Block shall commence on the later of the scheduled Billing Commencement Date and the date such Capacity Block achieves Ready for Service as certified pursuant to Section [Commissioning], including delivery of the commissioning agent’s certificate.",
    fixNote: "The density schedule draws the geometry. The RFS cross-reference takes the rent clock out of the operator’s letterhead and hands it to the commissioning agent, which is where E7 will pick up."
  },
  spar: {
    setup: "Helios’s deployment plan shows GPU rows at 120kW per rack with wide service aisles. Marcus flips the floor plan around to face you.",
    marcus: "Look at your own drawing. You’re using a third of the floor and all of the power. We sized this hall for a normal mix, and your layout strands seven thousand square feet of our white space that we can never sell, because there’s no power left behind it. So the space charge has to reflect the full hall, and honestly the per-kW rate should step up too, because concentrated load costs more to cool per kW than distributed load. That’s not a negotiating position, that’s thermodynamics.",
    options: [
      { text: "“Then we’ll take the extra seven thousand feet at no charge and use it for storage and staging, since we’re paying for it anyway.”", grade: 2, feedback: "Pragmatic, and getting staging space has real value. But you accepted his framing that Helios pays for the whole hall, and converted a pricing fight into a free-storage consolation prize. The structural question, who bears stranding risk in a power-based deal, went unanswered, and it will return at every expansion and renewal." },
      { text: "“Thermodynamics doesn’t bill by the square foot. This is a 36MW deal, priced per kW, and we’re consuming exactly 36MW. The hall geometry is your design choice, made before we signed. If concentrated load genuinely costs more to cool, show me that in the PUE, which we pay for under the power provisions, so charging it again in the space rate is double recovery. And stranded floor is the cost of selling power-dense deals, which is the business Ironvale chose to be in.”", grade: 3, feedback: "This lands every blow available. Per-kW pricing means stranding risk sits with the party that designed the hall. The PUE point is the killer: any genuine cooling inefficiency from dense load already flows to Helios through the power pass-through, so a density surcharge in the space rate recovers the same cost twice. Marcus retreats to asking for a modest minimum-space charge, which you can price." },
      { text: "“We’re sympathetic. Let’s split the stranded space cost 50/50 as a compromise.”", grade: 0, feedback: "You conceded a cost category that doesn’t belong to your client, then split it. Nothing in the deal structure makes Helios responsible for floor it never asked for. Splitting a phantom liability is not compromise, it’s a gift, and Marcus will book it and look for the next one." },
      { text: "“If density costs more to cool, that’s real, so let’s see the engineering. Give us the plant model showing the cooling penalty for our layout versus the standard mix.”", grade: 1, feedback: "Asking for engineering substantiation is a respectable move and sometimes the right opener. But you treated his strongest-sounding and weakest-actual claim as potentially valid and invited a deck of operator-authored numbers you’ll struggle to rebut. The structural answer (per-kW deal, PUE already carries cooling cost, stranding is his design risk) was available without homework." }
    ],
    counter: "In a per-kW deal, stranding risk belongs to the party that designed the hall geometry. And the cooling-cost argument is double recovery: any real inefficiency from concentrated load already flows to the customer through PUE-based power pass-throughs. If Ironvale wants protection, the honest instrument is a stated minimum space charge, priced visibly, not physics rhetoric in the rate."
  },
  bank: [
    { q: "From E2: an operator commits to “N+1 cooling.” What is the first clarifying question that determines whether that commitment means anything?", options: ["N+1 per what: per facility, per system, or per data hall, and is the spare shared", "Whether the chillers are air-cooled or water-cooled", "Whether N is an odd or even number", "Whether the facility also has N+1 generators"], correct: 0, explain: "A single shared spare across a whole plant satisfies “N+1” while leaving any maintenance window one failure away from thermal runaway. Scope of the +1, and whether maintenance consumes it, is the whole question, which is why concurrent maintainability beats equipment counts." },
    { q: "Why do average density caps fail dense AI deployments even when the math works out?", options: ["Cooling serves geometry (rows and zones), so a compliant hall average can still contain rows the plant physically cannot cool", "Because averages are recalculated monthly", "Because AI equipment draws power in direct current", "They don’t fail, since averages are the standard and operators must accommodate any layout under them"], correct: 0, explain: "Physics polices peaks, not averages. A 7.2kW hall average with 15kW rows can be unservable by row-pair CRAHs. The density exhibit must draw the layout: per-rack, per-row, per-hall, with cooling method per band." },
    { q: "What is stranded capacity and why does its allocation matter?", options: ["Capacity of one resource (space or power) left unsellable when the other runs out first, and whoever bears it loses real money, so it drives the space-vs-power pricing fight", "Power that the utility fails to deliver during peak hours", "Capacity reserved for redundancy that cannot count toward the customer grant", "Unused fiber strands in the meet-me room"], correct: 0, explain: "Power-dense deals consume all the power and a fraction of the floor. If the deal is priced per kW, the leftover floor is the operator’s design risk. Operators try to claw it back through full-hall space charges and density surcharges, hence the spar you just had." }
  ],
  card: {
    term: "Ramp Schedule",
    physical: "The tranche-by-tranche timetable on which capacity blocks (e.g., 6MW per quarter) are built, commissioned, and made available, reflecting the physical reality that a 36MW facility is delivered in stages as electrical and mechanical lineups complete.",
    contractual: "It carries two clocks, the operator’s delivery dates and the customer’s billing dates, and the draft will make yours hard and theirs soft unless each block’s billing is tied to certified RFS with delay remedies mirroring the payment obligation."
  }
},

/* ================= E5 CONNECTIVITY ================= */
{
  id: "e5", num: 5, icon: "🔌", title: "Connectivity",
  tagline: "Meet-me rooms, cross-connects, carrier neutrality, dark fiber, and diverse entry that actually diverges.",
  walk: [
    "Dee badges you into a room that looks nothing like the rest of the facility: dense racks of patch panels, yellow fiber cascading through overhead troughs, a dozen carriers’ logos on locked cabinets. “The meet-me room. Physically the least impressive room in the building and commercially the most leveraged. Every bit your client’s GPUs produce leaves through here, and every byte of training data arrives through here.”",
    "She lifts a single yellow jumper. “This is a cross-connect. Two ends of glass and maybe forty dollars of material. Operators bill three hundred a month for it, forever, and there are facilities where the meet-me room makes better margins than the data halls. Power gets the headlines in your deal. This room is where the quiet money is, and where one backhoe in the wrong easement can take your client offline no matter how many generators I keep fueled.”"
  ],
  concepts: [
    { term: "Meet-me room (MMR)", body: "The neutral interconnection space where carriers, customers, and the operator’s networks physically meet. Big facilities run two MMRs in different fire zones for redundancy. Who operates the MMR (the operator, or a third party) and what they charge to let parties connect is a governance question with a monthly invoice attached." },
    { term: "Cross-connect", body: "A physical cable (fiber, usually) between two parties’ equipment inside the facility, ordered through the operator and billed monthly (MRC) plus install (NRC). Trivial cost to provide, priced as a profit center, and a switching-cost moat: a customer with 200 cross-connects can’t leave easily. Cap the rates and the annual increases in the contract, per circuit type, including to third parties." },
    { term: "Carrier neutrality", body: "A <b>marketing</b> term meaning the operator lets multiple carriers serve the building without exclusivity or punitive terms. It is not a defined standard. The contractual substance: a stated right for any carrier of Customer’s choice to enter the facility, install in the MMR, and reach Customer’s premises on commercially reasonable terms, without the operator charging carriers rents that function as a toll on the customer." },
    { term: "Dark fiber vs lit services", body: "<b>Dark fiber</b> is the physical glass strand, leased unlit: the customer puts its own optics on each end and controls the capacity and security. <b>Lit</b> services are bandwidth products delivered by a carrier on shared infrastructure. AI campuses increasingly demand dark fiber between sites (for training clusters spanning buildings) and to cloud on-ramps. Dark fiber rights of way, conduit access, and the right to pull new fiber into the campus belong in the deal." },
    { term: "Diverse entry", body: "Two or more physically separate fiber entries into the building: separate vault, separate duct bank, separate path back to separate carrier POPs, ideally never coming within some stated distance of each other (25 feet is a common spec, practice varies). The failure mode is <b>nominal</b> diversity: two “diverse” paths that share a bridge crossing, a railroad easement, or a single duct bank for 400 yards because that’s where the conduit was. Diversity is a survey question, not a checkbox." },
    { term: "Latency", body: "Light in fiber travels about 200,000 km/s, roughly 5 microseconds per kilometer one way, about 1 millisecond of round trip per 100km, before equipment delay. You cannot negotiate physics, but you can negotiate route disclosure: the fiber route distance to the relevant exchange or cloud on-ramp, not the road distance. For Helios, latency to its cloud regions and data sources is a site-selection fact to verify, not an SLA to demand." }
  ],
  warStory: [
    "“Carrier hotel in a mid-market city, two fiber entries, north vault and south vault, diverse paths on every diagram anyone had ever drawn. A contractor boring for a water main hit a duct bank six blocks away. Both paths went dark. Turned out the ‘diverse’ routes converged into a single conduit run for one stretch under a river bridge, because thirty years ago that bridge was the only crossing and every carrier in town rented the same municipal conduit.",
    "The diagrams weren’t lies, exactly. They were drawn at a scale where the bridge didn’t show. Every customer in that building had redundant everything inside the walls, generators humming, dual UPS paths, and zero packets moving, for nineteen hours. Inside the fence I can give you five nines. The moment your bits leave my property, your protection is a survey of conduit maps, and almost nobody’s lawyer asks for the survey.”"
  ],
  bites: [
    { where: "Cross-connect pricing schedule", what: "Caps on MRC and NRC per circuit type, capped annual escalation, and the right to order cross-connects to any party in the building. Uncapped cross-connects are a renewal-leverage machine: by year five you can’t afford to leave." },
    { where: "Carrier access covenant", what: "Any carrier of Customer’s choice may enter, install, and serve Customer on commercially reasonable terms, with the operator barred from exclusivity deals and from carrier charges that function as tolls on Customer’s traffic." },
    { where: "Diverse entry verification", what: "Diversity stated as a physical spec (separate vaults, duct banks, and routes with minimum separation) plus a route survey or KMZ delivered as a condition, and a covenant to maintain diversity, not just to have it at signing." },
    { where: "Dark fiber and conduit rights", what: "Rights to bring owned or IRU fiber into the campus, conduit and riser access at stated rates, and no operator gatekeeping on the optics or capacity Customer runs on its own glass." },
    { where: "MMR governance", what: "Customer access to both MMRs, defined demarcation, hands-and-eyes service rates, and protections if the operator outsources or sells the MMR operation." }
  ],
  trap: {
    clause: "The Facility is carrier neutral, and Customer may order interconnection services from Operator’s then-current service catalog at Operator’s then-prevailing rates. Operator maintains diverse fiber entries to the Facility.",
    q: "Where is the trap?",
    options: [
      "“Carrier neutral” binds nothing, interconnection is priced at unilateral catalog rates that can escalate without limit, and “diverse entries” is asserted with no physical spec, survey, or maintenance covenant.",
      "Carrier neutrality is illegal under telecommunications law, exposing the customer to regulatory risk.",
      "The clause should specify single rather than diverse entry to reduce cost.",
      "Service catalogs cannot be incorporated into contracts by reference."
    ],
    correct: 0,
    explain: "Every operative word is self-referential: neutrality undefined, rates set by the operator’s own catalog (the cross-connect moat, fully armed), and diversity asserted as a present-tense fact with no spec, no survey, no covenant to keep it true when the operator re-routes conduits in year four. Nothing here is illegal or unenforceable. It is enforceable exactly as written, which is the problem.",
    fix: "Any carrier or network provider designated by Customer may install facilities in each Meet-Me Room and connect to the Premises on commercially reasonable, nondiscriminatory terms. Cross-connect charges shall not exceed the rates in Exhibit F, escalating not more than two percent per annum. The Facility shall at all times maintain not fewer than two physically diverse fiber entries, each in a separate vault and duct bank, with routes maintaining not less than twenty-five feet of separation, as evidenced by the route survey attached as Exhibit F-1, and Operator shall not reduce such diversity during the Term.",
    fixNote: "Diversity became a spec, a survey, and a covenant. The catalog became a capped exhibit. “Neutral” became a right your carriers can stand on."
  },
  spar: {
    setup: "You’ve asked for the cross-connect rate caps and the route survey. Marcus spreads his hands.",
    marcus: "The cross-connect rates are what fund the meet-me room: the staff, the security, the 24/7 hands-and-eyes. Cap them and you’re asking other customers to subsidize Helios. And the route survey, look, our fiber entries are diverse, but the routes beyond our property are carrier infrastructure. We don’t own those duct banks and we can’t warrant what Zayo and Lumen do with their own plant. You’re asking me to paper a promise about third-party property.",
    options: [
      { text: "“Every operator says the MMR is a cost center and every operator’s MMR margins say otherwise. Caps or we walk the connectivity exhibit.”", grade: 1, feedback: "The margin point is true and Marcus knows it, but as delivered it’s just a vibe with an ultimatum attached. He’ll ask which rates specifically are off-market and you’d better have the comp data. And you let the diversity half of his speech, the more dangerous half, go entirely unanswered." },
      { text: "“Fair point on third-party plant. We’ll drop the survey and rely on the carriers’ own diversity representations.”", grade: 0, feedback: "You just accepted the exact failure mode from Dee’s war story. Carrier diversity reps are per-carrier: each carrier’s two paths may be internally diverse while every carrier in the market shares the same bridge conduit. Only a route-level survey across providers reveals convergence, and you waived it because Marcus said the magic words “third party.”" },
      { text: "“Two separate issues, so let’s take them separately. On rates: fine, the MMR has costs, so put the rates in an exhibit at your current pricing and cap escalation at two percent. If today’s rates fund the room, today’s rates plus escalator keep funding it, and if you won’t freeze your own current pricing, this was never about cost recovery. On diversity: I’m not asking you to warrant Zayo’s duct banks. I’m asking what you already know: where your entries are, what routes serve them per the carriers’ own KMZs, and a covenant about the part you do control, your vaults and your conduits. Disclosure of third-party routes, warranty of your own plant.”", grade: 3, feedback: "Surgical. The escalator-on-current-rates move calls the cost-recovery bluff with the operator’s own numbers. And splitting diversity into disclosure (third-party routes, which the operator absolutely has in its site documentation) versus warranty (its own vaults and conduits) dissolves the “third-party property” objection completely. Marcus is now negotiating the escalator percentage, which means you won." },
      { text: "“Then we’ll contract with the carriers directly for diverse routes and leave Ironvale out of it entirely.”", grade: 2, feedback: "Directionally sensible, and Helios will indeed have its own carrier contracts. But carriers can only be diverse with respect to entries the operator builds and maintains, so you can’t actually leave Ironvale out: if both vaults share a duct bank for the last hundred yards on the operator’s campus, no carrier contract fixes it. You walked away from the one party whose plant you needed covenants on." }
    ],
    counter: "Split each issue against itself. Rates: accept that the MMR has costs by freezing the operator’s own current pricing in an exhibit with a capped escalator, which calls the cost-recovery framing honestly. Diversity: distinguish disclosure from warranty. The operator discloses the entry locations and carrier route data it already holds, and covenants the plant it does control, its vaults, conduits, and on-campus pathways. Nobody warrants third-party duct banks, and nobody hides behind them either."
  },
  bank: [
    { q: "From E1: what protects a single-corded piece of equipment in a dual-path facility?", options: ["A static transfer switch, which moves the load between two live paths in about 4 milliseconds", "An automatic transfer switch, which moves it in 30 seconds", "The UPS batteries, which power it directly for the outage duration", "Nothing, since single-corded equipment cannot be protected"], correct: 0, explain: "The STS switches between live A and B paths in about a quarter of an AC cycle, faster than power supplies notice. The ATS is the seconds-scale mechanical switch between utility and generator, a different job." },
    { q: "Why can two “diverse” fiber paths still fail together?", options: ["Nominal diversity: the routes converge into a shared duct bank, bridge crossing, or easement somewhere along the path, so one cut takes both", "Because fiber paths share light wavelengths", "Because diversity only applies to copper circuits", "They cannot, since diverse paths are physically incapable of simultaneous failure"], correct: 0, explain: "Diversity fails at the pinch points geography creates: bridges, rail crossings, municipal conduit. The fix is route-level verification (a survey or KMZ across carriers) plus a covenant to maintain separation, not a checkbox in a marketing deck." },
    { q: "Why do uncapped cross-connect rates matter more at renewal than at signing?", options: ["Hundreds of accumulated cross-connects become a switching-cost moat, so uncapped rates and escalators turn into pure leverage when the term expires", "Because cross-connects physically degrade and must be replaced at renewal", "Because regulators audit cross-connect pricing every renewal cycle", "They don’t, since cross-connect charges are immaterial rounding errors in a 36MW deal"], correct: 0, explain: "Each circuit is cheap; the dependency is not. A deployment wired into hundreds of circuits cannot credibly threaten to leave, and operators price renewals accordingly. Caps and escalation limits negotiated at signing are the only time you’ll ever have leverage on this." }
  ],
  card: {
    term: "Diverse Entry",
    physical: "Two or more physically separate fiber paths into the building, in separate vaults and duct banks, maintaining stated separation along their entire routes, so that no single cut, dig, or fire takes both.",
    contractual: "Must be papered as a physical spec plus a delivered route survey plus a covenant to maintain it, because “diverse” asserted as an adjective routinely conceals shared conduit that turns redundant infrastructure into a single point of failure."
  }
},

/* ================= E6 SLAs & AVAILABILITY MATH ================= */
{
  id: "e6", num: 6, icon: "📊", title: "SLAs & Availability Math",
  tagline: "What five nines actually buys, measurement windows, exclusion stacking, and chronic outage escape hatches.",
  walk: [
    "No tour today. Dee commandeers a conference room, writes 99.999% on the whiteboard, and circles it. “Marcus is going to put this number in front of your client like it’s a diamond. I’m going to show you what it weighs. Five nines is five minutes and sixteen seconds a year. Four nines is fifty-two and a half minutes. Three nines, which is what some SLAs net out to after the exclusions, is eight and three-quarter hours.”",
    "She caps the marker. “Here’s the industry’s open secret: the SLA percentage is the least important number in the SLA. The definitions decide what counts as down, the window decides how misses accumulate, the exclusions decide what never counts at all, and the remedies decide whether a miss costs the operator anything. I’ve seen facilities with worse uptime and better SLAs than their competitors, purely on drafting. Today you learn to weigh the diamond.”"
  ],
  concepts: [
    { term: "The nines, as minutes", body: "Availability percentages convert to allowed downtime: 99.9% = 8h 46m per year. 99.99% = 52.6 minutes. 99.999% = 5.26 minutes. 100% SLAs exist and are real commitments in 2N facilities, though remember an SLA is a price for failure, not a prevention of it. The conversion matters because credits, chronic-outage triggers, and your client’s risk model all run on minutes, not percentages." },
    { term: "Outage definition", body: "The load-bearing definition. Operator drafts want: total loss of power to <b>both</b> cords, lasting more than a stated number of consecutive minutes, measured at the operator’s equipment. Customer wants: any interruption or deviation (power or cooling) at the customer’s equipment that causes or requires shutdown, with no minimum duration, since a 50-millisecond drop crashes a training run as thoroughly as an hour. Where you land sets everything downstream." },
    { term: "Measurement window", body: "The period over which availability is calculated: monthly or annual. The same 99.99% allows 4.4 minutes per month measured monthly, but measured <b>annually</b> the operator can bank eleven perfect months and absorb a 52-minute outage without breaching. Annual windows let one bad night be amortized by months in which nothing happened. Customers want monthly." },
    { term: "Exclusion stacking", body: "Downtime that doesn’t count: force majeure, scheduled maintenance, customer acts, utility failure (read that one twice: in a facility whose entire purpose is surviving utility failure), emergency maintenance, “events beyond Operator’s reasonable control.” Each is arguable alone. Stacked, they can convert five nines into a number with no nines. The utility exclusion in particular swallows the deal: generators and UPS exist precisely because the grid fails." },
    { term: "Service credits", body: "The standard remedy: a percentage of monthly fees per increment of downtime, usually capped (often at 100% of one month) and usually styled as the <b>sole and exclusive remedy</b>. For an AI customer the math is brutal: a month of fees on a 36MW deal is real money, but an outage that idles a GPU fleet mid-training-run costs multiples of it. Credits are a deductible, not insurance. The fight worth having is the cap, the sole-remedy scope, and the escape hatch." },
    { term: "Chronic outage termination", body: "The escape hatch: the right to terminate (and ideally recover unamortized customer investment) after defined repeated failures, e.g., three SLA events in any twelve months, or any single outage exceeding a stated duration, or cumulative downtime crossing a threshold. Operators resist hard triggers and offer cure rights and root-cause-analysis process instead. Without a chronic trigger, the sole-remedy clause means the operator can fail indefinitely at a known, capped price." }
  ],
  warStory: [
    "“Facility in Texas, customer with a 99.99% monthly SLA, and the place had a sick static switch that dropped one path for thirty to forty seconds every few weeks. Six events in four months. Customer’s gear crashed every time, dual-corded but with one bad PDU mapping, that’s a story for the ops episode. Total downtime: about four minutes. Credits owed under the SLA: zero dollars. Each event was under the five-minute floor in the outage definition.",
    "Four minutes of downtime, six crashed production windows, zero remedy. The customer’s GC called me asking how that was possible, and I read her the definition over the phone: ‘continuous interruption exceeding five (5) minutes.’ The facility was never down five minutes. It was down forty seconds, repeatedly, forever. Drafting did that, not engineering. The fix existed the whole time: an event-based definition with no duration floor, and a chronic trigger counting events instead of minutes.”"
  ],
  bites: [
    { where: "“Outage” / “Service Interruption” definition", what: "Any deviation at the customer’s equipment (power or cooling, either path if it causes load loss), no minimum duration, measured at the PDU or rack. The five-minute floor in operator drafts is the single most expensive sentence in the SLA." },
    { where: "Measurement window", what: "Monthly, not annual. Annual windows amortize disasters across eleven good months. Credits and chronic triggers should both key off the monthly calculation." },
    { where: "Exclusions schedule", what: "Strike or narrow: utility failure (the facility’s whole job), emergency maintenance (cap hours, require notice), force majeure (carve back power and cooling to on-site systems). Scheduled maintenance only within defined windows from E9, with advance notice and no reduction below concurrent maintainability." },
    { where: "Credit schedule and cap", what: "Escalating credits per event severity, cap negotiated as high as leverage allows, and credits expressly not the exclusive remedy for chronic failure, gross negligence, or willful misconduct." },
    { where: "Chronic outage termination", what: "Hard triggers: N events in 12 months, any single event over X hours, or cumulative downtime over Y minutes in any quarter, with termination plus recovery of unamortized improvements and migration costs. This clause is the only thing that makes the credits cap tolerable." }
  ],
  trap: {
    clause: "Operator guarantees 99.999% Availability, calculated annually. An “Outage” means a continuous interruption of power to both power distribution paths serving the Premises exceeding five consecutive minutes, excluding interruptions caused by utility service failure, scheduled or emergency maintenance, or events beyond Operator’s reasonable control. Service credits as set forth herein are Customer’s sole and exclusive remedy for any Outage.",
    q: "Where is the trap?",
    options: [
      "Every element is hollowed: an annual window amortizes failures, the both-paths five-minute floor excludes most real events, the utility and emergency-maintenance exclusions erase the facility’s core function, and sole-remedy caps the damage at credits.",
      "99.999% is mathematically impossible for any facility to achieve, so the guarantee is illusory.",
      "The clause is fine for the customer, since five nines is the strongest commitment available in the market.",
      "The defect is purely the word “guarantees,” which should read “warrants” to be enforceable."
    ],
    correct: 0,
    explain: "Run the stack: annually, the operator banks 11 perfect months against any single event. Both-paths-five-minutes means the Texas pattern (repeated sub-minute single-path drops crashing your load) is definitionally never an outage. Utility failure excluded means the exact event the generators exist for doesn’t count. Emergency maintenance excluded means unplanned single-threading doesn’t count. And sole-remedy means whatever survives all that costs the operator, at most, capped credits. The headline five nines is real and irrelevant.",
    fix: "Operator shall provide 99.999% Availability, calculated monthly. A “Service Interruption” means any interruption of power or cooling at Customer’s equipment that causes or requires the shutdown of any of Customer’s IT load, with no minimum duration. Interruptions caused by failure of utility service shall not be excluded. Scheduled maintenance is excluded only if performed within the maintenance windows and notice requirements of Section [Operations] and only to the extent it does not reduce redundancy below concurrent maintainability. If three or more Service Interruptions occur in any twelve month period, or any Service Interruption exceeds four hours, Customer may terminate without penalty and recover its unamortized installation costs, and service credits shall not be Customer’s exclusive remedy for such chronic failure.",
    fixNote: "Each fix targets one device: window, definition floor, utility exclusion, maintenance bounds, and the chronic hatch that makes the credit cap survivable."
  },
  spar: {
    setup: "You’ve struck the utility-failure exclusion. Marcus looks genuinely wounded.",
    marcus: "Be reasonable. The utility is a regulated monopoly we don’t control. When ERCOT sheds load in a winter storm, that is the textbook definition of an event beyond our reasonable control, and every force majeure clause you’ve ever drafted says exactly that. We’ll stand behind our equipment, our staff, our facility. We cannot stand behind the Texas grid, and no operator in this market will sign up to insure it.",
    options: [
      { text: "“Every force majeure clause I’ve drafted also says force majeure doesn’t excuse obligations the contract specifically allocates. But fine, we’ll accept the exclusion if you extend the generator fuel commitment to 96 hours.”", grade: 2, feedback: "The first sentence is the right doctrine and the fuel trade has real value in an extended grid event. But you traded away the principle while citing it: with the utility exclusion intact, an outage during a grid event owes you nothing regardless of how much fuel is on site or whether the generators were even maintained. You bought more diesel for a facility that no longer has to use it." },
      { text: "“Marcus, what did Helios buy? Walk the chain with me: utility fails, generators start, UPS bridges, load never drops. That sequence is the product. Your own marketing calls it that. An exclusion for utility failure doesn’t allocate grid risk, it deletes the facility’s reason to exist, because the only time your backup systems are tested is precisely the moment your SLA goes dark. Here’s the language we’ll sign: utility failure excuses nothing by itself, and the SLA applies in full whenever on-site systems should have carried the load. If the grid is down longer than the fuel spec plus the refueling contract, that residual tail can be force majeure. That’s the part you actually don’t control.”", grade: 3, feedback: "This is the argument, delivered whole. You converted the philosophical fight into an engineering boundary: everything within the designed ride-through (UPS, generators, fuel spec, refueling) is the operator’s product and stays inside the SLA, and only the tail beyond design parameters is genuine force majeure. No operator can say out loud that its backup systems aren’t its responsibility, and you gave Marcus a real, bounded concession to carry home. This is how that clause actually settles in well-advised deals." },
      { text: "“Then Helios buys grid risk insurance and Ironvale reimburses the premium.”", grade: 1, feedback: "Creative, and parametric outage products do exist, but you’ve moved a contract allocation into an insurance market with thin capacity and priced-in exclusions of its own, while leaving the SLA exclusion standing. The operator’s generators still carry no SLA consequence when the grid blinks. Marcus reimburses a premium and keeps the structural win." },
      { text: "“No operator will sign it? Vantage, QTS, and two others have struck that exclusion for anchor tenants this year. We’ll send you the league table.”", grade: 2, feedback: "Market evidence is genuinely useful here and anchor tenants do win this point, so the bluff-call has teeth. But naming comps invites a comps war you can’t fully win from outside those deals, and you’ve made it a leverage contest instead of the engineering argument that actually corners him: the backup chain IS the product. Lead with physics, use comps as the closer." }
    ],
    counter: "Reframe the exclusion as an engineering boundary. The facility’s designed ride-through (UPS bridge, generator start, fuel spec, refueling contracts) is the product Helios is paying for, and it is only ever exercised during utility failure, so excluding utility failure deletes the SLA at the exact moment it matters. Concede the genuine tail: grid outages outlasting the designed fuel and refueling envelope can be force majeure. Everything inside that envelope stays inside the SLA."
  },
  bank: [
    { q: "From E3: an SLA promises hall temperature within the “ASHRAE allowable” range, averaged across supply sensors. Why can your racks cook while the SLA reads green?", options: ["Allowable reaches 32°C and averaging hides hot spots, so a compliant average coexists with recirculating hot rows at the rack inlets", "Because ASHRAE ranges only apply in winter months", "Because supply sensors measure humidity, not temperature", "It can’t, since any high reading anywhere breaches an averaged SLA"], correct: 0, explain: "Two devices from the cooling episode: the allowable-vs-recommended envelope gap (32°C vs 27°C ceilings) and the flattering measurement (averages and supply-side sensors instead of per-rack inlets). Same SLA anatomy as the nines: the percentage is fine, the definitions do the damage." },
    { q: "99.99% availability measured monthly versus annually: what’s the practical difference?", options: ["Monthly allows about 4.4 minutes of downtime per month before breach, while annual lets the operator amortize a 52-minute event across eleven perfect months", "There is none, since the percentage is identical", "Annual measurement is stricter because the year is longer", "Monthly measurement excludes weekends by convention"], correct: 0, explain: "Same percentage, different physics of accumulation. Annual windows let one catastrophic night disappear into the yearly average. Credits and chronic triggers should run on monthly math." },
    { q: "Why does a “continuous interruption exceeding five minutes” floor in the outage definition gut the SLA for an AI customer?", options: ["Sub-minute power events crash training runs and GPU clusters as completely as long outages, yet under a duration floor they never count as outages at all", "Because five minutes is longer than UPS battery runtime", "Because interruptions are only measurable in hourly increments", "It doesn’t, since short interruptions are harmless to modern hardware"], correct: 0, explain: "The Texas war story: six sub-minute events, six crashed production windows, zero credits. Compute loads fail on transients. The customer definition needs no minimum duration and should key off impact at the customer’s equipment." }
  ],
  card: {
    term: "Chronic Outage Termination",
    physical: "A pattern of repeated failures (e.g., three SLA events in twelve months, or one event over a stated number of hours) indicating the facility or its operation is systemically unreliable rather than unlucky.",
    contractual: "The only remedy that escapes the capped, sole-remedy service credit regime: a hard termination trigger with recovery of unamortized investment, without which the operator can fail indefinitely at a known, budgeted price."
  }
}
];
