/* CRITICAL LOAD — episode data E1-E3 */
window.DATA1 = [

/* ================= E1 POWER CHAIN ================= */
{
  id: "e1", num: 1, icon: "⚡", title: "The Power Chain",
  tagline: "Utility to rack: transformers, switchgear, UPS, generators, and why kW is not kVA.",
  walk: [
    "Dee badges you through a steel door marked ELECTRICAL GALLERY A and the sound hits first, a 60-hertz hum you feel in your sternum. Gray cabinets the size of refrigerators in ranked rows, thick orange conduit overhead, yellow tape on the floor marking arc-flash boundaries. “Don’t cross the tape. The gear behind it can vaporize a wrench.”",
    "She walks you to a window over the yard: transformers the size of shipping containers, steel lattice, transmission lines marching to the horizon. Beyond them, twenty diesel generators in sound-attenuated enclosures, each bigger than a school bus.",
    "“Thirty-six megawatts comes in from the utility as something you absolutely cannot plug a server into, and we transform, condition, back up, and switch it about six times before it’s usable. Every one of those steps is a place where the contract either protects Helios or quietly doesn’t. Walk the chain with me.”"
  ],
  concepts: [
    { term: "Utility interconnect", body: "The physical and contractual connection to the grid, governed by an agreement between the <b>operator</b> and the utility. Your client is not a party to it. Power arrives at transmission voltage, typically 69kV to 230kV for a campus this size. The interconnect has its own capacity number, its own delivery schedule, and its own force majeure, and in hot markets new large interconnects take <b>years</b>. That risk flows downhill into your delivery dates." },
    { term: "Substation and transformers", body: "The substation steps transmission voltage down to medium voltage (12.47kV to 34.5kV) for distribution around the campus. Transformers then step down again to utilization voltage, typically 480V or 415V at the racks. A transformer is rated in <b>MVA</b>, not MW. Hold that thought. Also: who owns the substation (utility, operator, or shared) determines whose outage it is when it fails." },
    { term: "Switchgear", body: "Industrial-grade circuit breakers and bus bars that route, isolate, and protect circuits. Redundancy physically lives here: an “A side” and “B side” are literally separate lineups of switchgear. Lead times on medium-voltage gear run 40 to 60+ weeks right now, which is why delivery delays so often trace back to this room." },
    { term: "UPS (uninterruptible power supply)", body: "The bridge. When utility power blinks, the UPS carries the IT load on stored energy until generators come up. <b>Double-conversion online</b> UPS (the data center standard) converts AC to DC and back continuously, so the IT load never sees raw utility power. Batteries give roughly 4 to 10 minutes at full load. Flywheels give 15 to 30 <b>seconds</b>. Both are ride-through, not backup." },
    { term: "Generators", body: "The actual backup power plant. Diesel engines, typically 2 to 3MW each, that must start, reach speed and voltage, and accept load in roughly 10 to 15 seconds, inside the UPS battery window. On-site fuel is usually specced at 24 to 72 hours at full load, with refueling contracts behind it. Some markets restrict runtime via air permits, which changes the math. Ask." },
    { term: "ATS vs STS", body: "Both transfer switches, not interchangeable. An <b>ATS (automatic transfer switch)</b> is mechanical and moves a load between utility and generator in <b>seconds</b>. A load on an ATS alone goes down during transfer, which is what the UPS covers. An <b>STS (static transfer switch)</b> is solid-state and moves a load between two <b>live</b> paths in about 4 milliseconds, a quarter of an AC cycle, fast enough that the server never notices. STSs are how single-corded gear survives in a dual-path facility." },
    { term: "kW vs kVA", body: "kW is <b>real power</b>, the work actually done. kVA is <b>apparent power</b>, what wires and transformers must be sized to carry. The ratio is <b>power factor</b> (kW = kVA × PF). IT gear runs PF of roughly 0.95 to 1.0, but electrical equipment is rated in kVA or MVA at an assumed PF, often 0.8 or 0.9. So “36 of capacity” is a different physical quantity depending on the unit. A 40 MVA system at 0.9 PF is 36MW. <b>Your deal should be written in kW, full stop.</b>" },
    { term: "Critical load vs total load", body: "<b>Critical load</b> (or “critical IT load”) is the power delivered to the customer’s computing equipment, conventionally measured at the UPS output or the PDUs downstream. <b>Total load</b> is everything the facility draws: critical load plus cooling (enormous), plus electrical losses in every transformer and UPS, plus house loads. A “36MW” facility measured at the utility meter delivers maybe 26 to 29MW of actual critical load. That spread is a quarter of your client’s deal." }
  ],
  warStory: [
    "“Facility I consulted on after the fact, 2014-ish. Utility sag, textbook event. UPS caught the load, batteries holding, generators started in eleven seconds, beautiful. And the load still dropped nine minutes later, because the ATS feeding that lineup had been left in manual bypass after maintenance two weeks earlier.",
    "The generators were running, at speed, making power, and electrically going nowhere. Batteries ran to zero with the cavalry idling in the parking lot. Every component worked. The system failed, on a human procedure. Remember that when someone shows you a spec sheet as proof of reliability. Specs don’t trip outages. Sequences do.”"
  ],
  bites: [
    { where: "Definition of “Critical Load” / “Customer Power”", what: "THE definition of the deal. Must specify kW (not kVA or MVA), the measurement point (UPS output or PDU), and that it excludes mechanical load, house load, and electrical losses." },
    { where: "Delivery conditions / RFS", what: "Utility interconnect energization is the single most likely delay, and Marcus wants it treated as force majeure. Push for it as an operator milestone with remedies, or at minimum a hard outside date with termination." },
    { where: "SLA / outage definition", what: "Operator wants “outage” measured at the UPS output. Customer wants it at the rack or PDU, because ATS misoperations, STS failures, and downstream breaker trips all live between those two points." },
    { where: "Maintenance exclusions", what: "UPS bypass windows and generator test transfers. If the SLA excludes “scheduled maintenance” without bounding it, the operator can strip your UPS protection monthly and owe nothing when the bypass goes wrong." },
    { where: "Ramp / phasing", what: "Power is delivered in blocks as electrical lineups are commissioned. The ramp schedule must tie each block to a dated delivery obligation, not “as commissioned.”" }
  ],
  trap: {
    clause: "Operator shall provide Customer with 36 MVA of power capacity for the Premises, as measured at the output of the Facility substation, subject to the design criteria set forth in Exhibit C.",
    q: "Where is the trap?",
    options: [
      "The capacity is stated in MVA and measured at the substation, so power factor assumptions and every downstream loss, including cooling, come out of the customer’s number.",
      "The clause fails to state that the power will be available 24/7, so the operator could curtail it at night.",
      "“Subject to Exhibit C” is improper incorporation by reference and would be unenforceable.",
      "36 MVA is simply too small a number for a 36MW deal and should be grossed up to 40 MVA."
    ],
    correct: 0,
    explain: "Three devices stack: MVA at the Exhibit C power factor (0.9) is 32.4MW before anyone speaks. Measuring at the substation output means transformer losses, UPS losses, and arguably the entire mechanical load count against the 36. And the operative grant is subordinated to an engineering exhibit the lawyers never read, where the PF assumption actually lives. Incorporation by reference is fine as drafting. The trap is what the exhibit says.",
    fix: "Operator shall make available to Customer, twenty-four hours per day, seven days per week, 36 MW of Critical IT Load. “Critical IT Load” means electrical capacity for Customer’s computing and network equipment, expressed in kW of real power, measured at the output of the PDUs serving the Premises. Critical IT Load excludes all mechanical load, house load, electrical distribution losses, and any redundant or reserve capacity maintained by Operator. In the event of any conflict between this Section and Exhibit C, this Section controls.",
    fixNote: "The last sentence carries the whole structure. The exhibits are where engineers negotiate against lawyers and win."
  },
  spar: {
    setup: "Marcus slides a redline across the table: your “Critical IT Load” definition struck, “36 MVA at the substation output” restored.",
    marcus: "Your markup asks us to warrant a number we don’t physically control. We deliver power through your PDUs at your power factor. If Helios racks run at 0.92 instead of 0.98, the same electrons are fewer of your “kW,” and suddenly we’re in breach because of your hardware. That’s why the industry contracts in kVA at a defined upstream point. The substation is the last point that’s one hundred percent within our design envelope.",
    options: [
      { text: "“Then let’s split the difference. We’ll take the kVA framing if you move the measurement point from the substation to the UPS output.”", grade: 1, feedback: "You just traded away the unit, which was the bigger half of the trap. At 0.9 assumed PF you gave back 3.6MW, about ten percent of the deal, to win a measurement point Marcus would likely have conceded anyway. Never horse-trade a definition you haven’t priced." },
      { text: "“Fine. But we want a representation that the facility’s power factor assumptions are commercially reasonable and consistent with industry standards.”", grade: 0, feedback: "A rep about reasonableness of an assumption is unfalsifiable comfort language. Marcus signs it happily, the deal stays in MVA, and your client still bought 32.4MW. You answered a physics argument with boilerplate, and he noticed." },
      { text: "“The PF risk is real but it’s tiny and it’s ours to manage. Modern IT gear runs 0.95-plus, and we’ll accept a floor: the kW commitment holds so long as Helios maintains aggregate power factor at or above 0.95. What we won’t accept is the substation measurement point, because that makes Helios pay for your transformer losses, your UPS losses, and your cooling out of our 36.”", grade: 3, feedback: "This is the move. You conceded the one true fact in his speech (load PF is the customer’s), bounded it with a number that costs Helios nothing, and isolated the real trap, which is the measurement point quietly converting total load into the customer’s capacity number. Marcus has nowhere to go except to admit the substation point was about losses, not physics." },
      { text: "“Every operator deal we’ve papered this year is in kW at the PDU. If Ironvale can’t match market, we have two other sites shortlisted.”", grade: 2, feedback: "Leverage is real and kW-at-the-PDU genuinely is common in hyperscale deals, so this can work. But you argued market instead of physics, and Marcus will come back with his own “market” deck and a story about why your comps are different. You had a winning technical answer (the PF floor) and didn’t use it, so the point stays open instead of closing." }
    ],
    counter: "Concede the only true fact (power factor of the IT load belongs to the customer) and cap it: the kW commitment holds so long as Helios maintains aggregate PF at or above 0.95, which modern gear clears easily. Then isolate the real device: measuring at the substation makes the customer pay for the operator’s transformer losses, UPS losses, and mechanical load out of its own capacity number. That isn’t physics, it’s margin."
  },
  bank: [
    { q: "A 40 MVA UPS system at an assumed power factor of 0.9 delivers how much real power?", options: ["36 MW", "40 MW", "44.4 MW", "32.4 MW"], correct: 0, explain: "kW = kVA × PF, so 40 MVA × 0.9 = 36MW. This is exactly why the unit in the capacity grant matters: the same nameplate is a different deal at a different assumed PF." },
    { q: "What does an STS do that an ATS cannot?", options: ["Transfer a live load between two power paths in about 4 milliseconds, fast enough that servers never notice", "Start the generators automatically on utility failure", "Convert AC power to DC for the UPS batteries", "Step medium voltage down to utilization voltage"], correct: 0, explain: "The STS is solid-state and switches in about a quarter cycle between two live paths. The ATS is mechanical, takes seconds, and classically moves load between utility and generator, with the UPS covering the gap." },
    { q: "Why is the measurement point in the capacity definition worth real money?", options: ["Measured upstream (e.g., at the substation), electrical losses and mechanical load count against the customer’s capacity number", "Upstream measurement points are less accurate metering technology", "Downstream measurement increases the utility’s demand charges", "The measurement point determines which party owns the transformers"], correct: 0, explain: "Between the substation and the PDU sit transformer losses, UPS losses, and the entire cooling plant. Measured upstream, all of it comes out of the customer’s 36. That spread can be a quarter of the deal." }
  ],
  card: {
    term: "Critical IT Load",
    physical: "The real power, in kW, actually delivered to the customer’s computing equipment, conventionally measured at the UPS output or PDU, after all upstream losses and excluding cooling and house loads.",
    contractual: "The unit, measurement point, and exclusions in this single definition set the size of the deal; written in MVA at an upstream point, the same “36” can be worth 25% less."
  }
},

/* ================= E2 REDUNDANCY ================= */
{
  id: "e2", num: 2, icon: "🔁", title: "Redundancy",
  tagline: "N, N+1, 2N, concurrent maintainability vs fault tolerance, and what a “Tier III” claim actually certifies.",
  walk: [
    "Dee takes you up a steel stair to a mezzanine overlooking two identical electrical galleries, separated by a fire-rated wall. “Gallery A, Gallery B. Everything you saw yesterday exists twice. Separate utility feeds, separate UPS lineups, separate distribution, all the way to two cords on every server. That wall is rated two hours, and the deal you’re papering is mostly about what that duplication legally means.”",
    "She raps a knuckle on the railing. “Here’s the thing nobody tells lawyers: redundancy isn’t a thing, it’s a topology, and operators describe topologies with letters that have no legal meaning until you define them. N, N+1, 2N. Marcus will use them like they’re ASTM standards. They’re not. They’re shorthand, and shorthand is where margin hides.”"
  ],
  concepts: [
    { term: "N", body: "N is the capacity actually required to serve the design load. If the facility needs five chillers to cool the load, N = 5. “N” as a design means zero spare: any failure or any maintenance drops load. Nobody sells N for critical load, but pieces of N hide inside systems that are otherwise redundant, and that’s what you hunt for." },
    { term: "N+1 (and N+2)", body: "Need plus one spare. Five chillers required, six installed. Survives <b>one</b> failure or supports <b>one</b> unit in maintenance, but not both at once. The spare is usually shared across the whole system, so the question that matters is: plus one <b>per what</b>? N+1 per facility is much weaker than N+1 per system per gallery." },
    { term: "2N", body: "Two complete, independent systems, either able to carry the full load alone. The A/B galleries you’re looking at. Survives a failure <b>during</b> maintenance, because the entire second path is live. The expensive gold standard for electrical paths. 2N on <b>mechanical</b> (cooling) is rarer and operators resist committing to it." },
    { term: "Distributed and block redundant", body: "Middle topologies that deliver “2N-ish” protection at lower cost. <b>Distributed redundant</b> (often “3N/2”): three paths each sized for half the load, any two can carry it. <b>Block redundant</b>: a shared reserve block backs up multiple primary blocks via STSs. Both are legitimate engineering. Both also mean the marketing word “fully redundant” needs a topology diagram behind it before you accept it in a contract." },
    { term: "Concurrent maintainability", body: "The property that <b>any</b> component can be taken out of service for planned maintenance without dropping critical load. This is an operational promise, not an equipment count, and it is the single most valuable redundancy commitment a customer can get in writing, because maintenance happens constantly and forever." },
    { term: "Fault tolerance", body: "The stronger property: the facility survives an <b>unplanned</b> failure, including a single failure anywhere in the topology, without impact to critical load. Concurrent maintainability handles the scheduled wrench. Fault tolerance handles the 3am surprise. A facility can be the first without being the second." },
    { term: "Uptime Institute Tiers: what’s actually certified", body: "Uptime’s Tier I-IV is a certification regime, not adjectives. Tier III = concurrently maintainable. Tier IV = fault tolerant. Crucially, certification comes in stages: <b>design documents</b>, then the <b>constructed facility</b>, then optionally operations. A facility “designed to Tier III standards” may never have been certified at all, and a design certificate says nothing about what got built after value engineering. “Tier III equivalent” is a marketing phrase with no auditor behind it." }
  ],
  warStory: [
    "“Big colo facility, mid-2010s, sold as ‘N+1 everything.’ True statement, as far as it went. The +1 chiller was shared across the entire plant. Maintenance window opens, one chiller down for an overhaul, facility is now at exactly N. Two hours into the window, a compressor on another chiller trips on high head pressure. Now they’re at N minus 1 on a July afternoon.",
    "White space went from 72 degrees to 95 in eleven minutes. Thermal runaway is faster than diesel. Servers started thermal-throttling, then shutting down, and the customer’s ‘N+1’ facility ate a four-hour outage without a single piece of equipment failing unexpectedly except one compressor. N+1 was true. It just wasn’t true during maintenance. That’s the whole difference between an equipment count and concurrent maintainability.”"
  ],
  bites: [
    { where: "Design criteria exhibit", what: "The redundancy commitment belongs in a system-by-system table: electrical path, UPS, generators, cooling, controls. One word like “Tier III” or “N+1” covering the whole facility is doing too much work, deliberately." },
    { where: "Performance standard vs design description", what: "Operator wants redundancy as a one-time design rep (“designed to N+1”). Customer wants a continuing operational covenant: the facility shall at all times be operated so that planned maintenance does not interrupt critical load." },
    { where: "SLA exclusions", what: "If “scheduled maintenance” is an SLA exclusion AND the facility isn’t contractually concurrently maintainable, the operator can take your redundancy away on notice and owe nothing when single-threaded operation goes wrong." },
    { where: "Certification conditions", what: "If the deal is sold on a Tier claim, make actual Uptime certification of the constructed facility a delivery condition or a rep. “Designed to Tier III principles” survives literally any building." },
    { where: "Change control", what: "Operators modify plants over a 15-year term. Without a covenant not to degrade the redundancy topology below the Exhibit C baseline, the 2N you bought can become N+1 by capital project in year six." }
  ],
  trap: {
    clause: "The Facility shall be designed in accordance with Uptime Institute Tier III principles, with N+1 redundancy for critical systems, as further described in Exhibit C.",
    q: "Where is the trap?",
    options: [
      "“Designed in accordance with Tier III principles” is a one-time design claim with no certification, no operational covenant, and an undefined N+1 scope, so nothing here survives value engineering or a maintenance window.",
      "Tier III is the wrong tier to reference, because AI workloads always require Tier IV facilities.",
      "N+1 and Tier III are inconsistent standards, which makes the clause void for vagueness.",
      "The clause should say “Tier 3” with a numeral, since Uptime Institute uses numerals in its certifications."
    ],
    correct: 0,
    explain: "Three soft spots: “designed in accordance with…principles” is not certification and binds nobody after the design phase. N+1 “for critical systems” doesn’t say per what, or which systems, so a single shared spare can satisfy it. And it’s all design description, no continuing covenant, so the operator can run the plant single-threaded during maintenance and point at this clause as satisfied. (Uptime actually uses Roman numerals, but that’s trivia, not a trap. And plenty of AI deals are in concurrently maintainable, not fault tolerant, facilities.)",
    fix: "Operator shall design, construct, and at all times operate the Facility so that it is concurrently maintainable, such that any single component of the electrical or mechanical infrastructure may be removed from service on a planned basis without interruption of or reduction in Critical IT Load. Without limiting the foregoing, the Facility shall maintain the system-level redundancy set forth in the Redundancy Table in Exhibit C, including 2N electrical paths from utility entry through PDU and not less than N+1 mechanical capacity per data hall. Operator shall not modify the Facility in a manner that reduces the redundancy below this Section’s requirements.",
    fixNote: "Note the shift from an adjective about the design to a covenant about operations, plus a no-degradation promise that runs for the term."
  },
  spar: {
    setup: "You’ve asked for Uptime Tier III Certification of the Constructed Facility as an RFS condition. Marcus leans back.",
    marcus: "Certification is a plaque. It’s seven figures of fees and consultants crawling our site for months, and it certifies a snapshot. Our design partner is Uptime-accredited, the facility is Tier III equivalent, and frankly half the hyperscale industry has stopped paying for the stamp. Your client is buying outcomes, and the outcomes live in the SLA. If we miss, we pay credits. Why are we paying Uptime for something the SLA already gives you?",
    options: [
      { text: "“Because our investment committee requires the certificate. It’s a box we can’t uncheck, so Ironvale needs to price it in or we can’t transact.”", grade: 1, feedback: "Appeal to internal process is honest but weak, and it invites exactly one response: a price increase to cover the certification, paid by your client. You also implicitly accepted his frame that the certificate is just a formality with no substantive content. Marcus will remember that in the SLA negotiation." },
      { text: "“He’s right that certification is partly theater. Drop it, and we’ll take a higher service credit percentage instead.”", grade: 0, feedback: "You traded a structural protection for credits, and credits are capped, excluded, and sole-remedy by design. An uncertified, non-concurrently-maintainable facility will generate outage events whose real cost to an AI company (idle GPU fleets, missed training runs) exceeds any credit schedule by orders of magnitude. Marcus would shake on this before you finished the sentence." },
      { text: "“The SLA pays us pennies after the fact. What I actually want is the property the certificate verifies. So here’s the trade: drop the certification requirement, and in exchange the contract states the concurrent maintainability requirement as an operating covenant, we get the full topology in Exhibit C with a no-degradation clause, and our engineer gets audit rights to verify it, at RFS and annually.”", grade: 3, feedback: "Exactly. You separated the stamp from the substance. Certification was always a proxy for one verifiable property, concurrent maintainability, and you converted it into a covenant plus inspection rights, which is stronger than a one-time snapshot anyway. You also gave Marcus a real concession to take back to his deal team, so it closes." },
      { text: "“If it’s Tier III equivalent, then certification should be cheap and easy. The fact that you’re fighting this hard tells me the facility wouldn’t pass.”", grade: 2, feedback: "Punchy, and there’s truth in it: ‘equivalent’ claims often do hide single-threaded valves or shared spares that certification would catch. But it’s a gotcha, not a position. Marcus calmly cites the real cost and schedule burden of certification, offers nothing, and you’ve spent credibility without getting language. Use the suspicion to justify audit rights, not as the argument itself." }
    ],
    counter: "Separate the stamp from the substance. The certificate is a proxy for one property: concurrent maintainability. Offer to drop certification in exchange for that property stated as a continuing operating covenant, a full system-level Redundancy Table in the exhibit, a no-degradation clause, and independent engineering audit rights at RFS and annually. That package is stronger than the plaque."
  },
  bank: [
    { q: "A facility advertises N+1 cooling with one shared spare chiller plant-wide. During a planned chiller overhaul, another chiller fails. What just happened?", options: ["The plant is at N-1 and will likely lose the thermal battle, because shared-spare N+1 cannot cover a failure during maintenance", "Nothing, because N+1 means the facility survives any two concurrent events", "The UPS carries the cooling load until the chiller restarts", "The spare chiller automatically doubles its output to compensate"], correct: 0, explain: "N+1 with a shared spare covers one event. Maintenance consumed the spare, the failure took the plant below N, and heat wins in minutes. This is the gap between an equipment count and concurrent maintainability. (And UPSs carry IT load, not chillers.)" },
    { q: "What is the difference between concurrent maintainability and fault tolerance?", options: ["Concurrent maintainability covers planned removal of any component without load loss, fault tolerance covers unplanned single failures without load loss", "They are synonyms used by different certification bodies", "Concurrent maintainability applies to mechanical systems, fault tolerance to electrical systems", "Fault tolerance is the cheaper, weaker standard of the two"], correct: 0, explain: "Tier III = concurrently maintainable (the planned wrench). Tier IV = fault tolerant (the 3am surprise). A facility can be the first without being the second, and the contract should say which one you bought, per system." },
    { q: "What does “Tier III equivalent” on an operator’s deck actually certify?", options: ["Nothing, it is a self-declared marketing phrase with no auditor behind it", "That Uptime Institute certified the constructed facility", "That the design documents were certified but construction is pending", "That the facility passed integrated systems testing at full load"], correct: 0, explain: "Uptime certification is a specific regime with stages (design documents, constructed facility, operations). “Equivalent,” “designed to Tier III principles,” and similar phrasing means no third party ever verified anything. If the deal is sold on the claim, paper the substance: concurrent maintainability as a covenant plus audit rights." }
  ],
  card: {
    term: "Concurrent Maintainability",
    physical: "The facility property that any single electrical or mechanical component can be taken out of service for planned maintenance without dropping critical load, which requires genuinely independent redundant paths, not just spare units.",
    contractual: "The most valuable redundancy commitment a customer can get, because it must be written as a continuing operating covenant with a no-degradation clause, not as a one-time design adjective like “Tier III equivalent.”"
  }
},

/* ================= E3 COOLING ================= */
{
  id: "e3", num: 3, icon: "❄️", title: "Cooling",
  tagline: "CRAHs, chillers, containment, ASHRAE envelopes, and why AI density breaks legacy cooling promises.",
  walk: [
    "The data hall is louder than the electrical gallery and colder at your ankles than your face. Dee walks you down a cold aisle, racks on both sides, clear plastic doors capping each end of the aisle and panels overhead. “Feel that? Cold air is money. Every cubic foot we let it mix with hot air is money on fire. That’s what the containment is for.”",
    "At the end of the hall she pushes through a door into the gray space: humming units the size of minivans lined against the wall, chilled water pipes overhead thick as your torso, wrapped in insulation and labeled SUPPLY 44°F and RETURN 60°F. “Heat is the actual product of a data center, counselor. Compute is a byproduct. Thirty-six megawatts in means thirty-six megawatts of heat out, every second, forever, and the machinery that moves that heat is about to become the most contested exhibit in your deal.”"
  ],
  concepts: [
    { term: "CRAC vs CRAH", body: "The minivan-sized units at the hall’s edge. A <b>CRAC</b> (computer room air conditioner) has its own refrigerant compressor, like a giant window unit. A <b>CRAH</b> (computer room air handler) is just fans and a coil fed with <b>chilled water</b> from a central plant. Big facilities run CRAHs plus chillers because central plants are far more efficient at scale. Which one you have determines what fails and how it fails." },
    { term: "Chillers and heat rejection", body: "The chiller is the machine that makes chilled water (typical supply 44 to 60°F, with modern plants running warmer for efficiency). It moves heat from the water loop to the outside world via cooling towers (evaporative, water-hungry) or dry coolers. The chilled water loop is a single shared circulatory system, which is why “2N cooling” is a much bigger claim than “2N power” and why operators resist it." },
    { term: "Economizers (free cooling)", body: "When outside air is cold or dry enough, the plant bypasses the compressors and cools for nearly free, either by bringing filtered outside air in (<b>air-side</b>) or by cooling the water loop directly (<b>water-side</b>). Hours of free cooling per year drive PUE, and PUE drives the customer’s power bill (E8). Climate is a deal economics input." },
    { term: "Containment", body: "Physical separation of hot and cold air. <b>Cold aisle containment</b> caps the cold aisle with doors and ceilings, <b>hot aisle containment</b> ducts exhaust into a sealed return plenum. Without containment, hot exhaust recirculates into intakes and the densities in your deal simply don’t work. Containment requirements and who pays for them show up in the work letter." },
    { term: "ASHRAE envelopes", body: "ASHRAE publishes the thermal envelopes everyone contracts around. The <b>recommended</b> envelope for inlet air is 18 to 27°C (64.4 to 80.6°F). The <b>allowable</b> A1 envelope stretches to 15 to 32°C. The contract question with real money behind it: does the SLA promise recommended or merely allowable, and is it measured <b>at the server inlet</b> or somewhere flattering like the CRAH discharge? Those can differ by 10+ degrees." },
    { term: "WUE", body: "Water usage effectiveness: liters of water per kWh of IT load. Evaporative cooling drinks millions of gallons in summer. Increasingly regulated, increasingly an ESG reporting pass-through, and occasionally a permit risk to the facility itself in drought-prone markets." },
    { term: "The high-density shift", body: "Legacy air cooling tops out around 20 to 40kW per rack even with good containment. AI racks now ship at 80 to 130kW+, which air physically cannot remove. The new stack: <b>rear-door heat exchangers</b> (water-cooled rack doors, roughly 40 to 80kW), <b>direct-to-chip</b> liquid cooling (cold plates on the silicon, fed by CDUs, 80 to 150kW+ per rack), and <b>immersion</b> (servers submerged in dielectric fluid, niche but real). Every legacy cooling commitment, SLA temperature term, and density schedule was written for air. AI deals break them all, and the retrofit cost question is exactly where Marcus is most creative." }
  ],
  warStory: [
    "“Pacific Northwest facility, summer 2021, the heat dome. Plant was designed around generous free-cooling hours and an outside design temperature of 89°F, because that was the hundred-year number when it was built. The thermometer hit 116. Chillers that had never run flat-out in their lives ran flat-out and started tripping on condenser pressure, one after another, like dominoes lying down.",
    "The operator started load-shedding cooling to the halls with the weakest contracts first. Read that again: the engineering decision about whose servers cooked was made by comparing SLA exclusion language. The customers whose deals said ‘outside design conditions’ was a force majeure event got the warm air. The deals with absolute inlet temperature commitments got the chilled water. Your exhibit is a priority claim on a finite resource. Draft it like one.”"
  ],
  bites: [
    { where: "Temperature/humidity SLA", what: "The commitment should be rack inlet temperature within the ASHRAE recommended envelope, measured at defined sensor locations at the server inlet. “Average hall temperature” or “CRAH discharge temperature” are flattering proxies that can coexist with cooked servers." },
    { where: "Density schedule", what: "kW per rack, per row, and per hall, with the cooling method specified per density band. An average density across the hall lets the operator deny your real layout (dense rows plus empty rows) while technically honoring the average." },
    { where: "Liquid cooling provisioning", what: "For AI loads: who designs, installs, owns, and maintains the CDUs, manifolds, and rack-level plumbing. Where the demarcation point sits (facility water loop vs technology cooling loop) determines who eats a leak, a pump failure, and the retrofit capex." },
    { where: "Force majeure / design conditions", what: "Operators exclude performance when ambient exceeds “design conditions.” With climate volatility, demand the design condition be stated as a number (e.g., ASHRAE N=20 extreme), and resist treating mere heat waves as force majeure." },
    { where: "Water and utilities pass-through", what: "Evaporative plants pass through water costs and risk. Cap the pass-through methodology, and get reporting on WUE if Helios has ESG disclosure obligations." }
  ],
  trap: {
    clause: "Operator shall maintain temperature in the Data Hall within the ASHRAE A1 allowable range, measured as the average of supply air sensors within the Data Hall, except during periods when outside ambient conditions exceed the Facility design parameters.",
    q: "Where is the trap?",
    options: [
      "Allowable instead of recommended, averaged supply-air sensors instead of rack inlets, and an undefined design-conditions carve-out: each device independently lets servers cook while the SLA reads green.",
      "ASHRAE A1 does not exist as a classification, so the clause references a phantom standard.",
      "Temperature SLAs are unnecessary because servers contain their own thermal protection.",
      "The clause fails to specify Fahrenheit or Celsius, which makes it unenforceable."
    ],
    correct: 0,
    explain: "Three stacked devices. A1 allowable runs to 32°C (89.6°F) at the inlet, far above the 27°C recommended ceiling, so “within allowable” permits chronically hot operation. Averaging supply sensors hides hot spots: the average can be 75°F while your densest row recirculates at 95. And “design parameters” is undefined and operator-controlled, a private force majeure. A1 is a real ASHRAE class, and onboard thermal protection means throttling and shutdown, which is precisely the harm.",
    fix: "Operator shall maintain supply air at the inlet of each of Customer’s racks within the ASHRAE recommended envelope of 18°C to 27°C, measured continuously at sensor locations at the top, middle, and bottom of rack inlets as set forth in Exhibit D. An exceedance at any sensor for more than fifteen consecutive minutes constitutes a Cooling SLA Event. The Facility design ambient condition is the ASHRAE 20-year extreme for the Facility location, and ambient conditions at or below that value shall not excuse performance.",
    fixNote: "Numbers, sensor locations, and a stated design ambient. Every word the operator must measure is a word the operator cannot reinterpret."
  },
  spar: {
    setup: "Helios wants 40 racks at 100kW each, direct-to-chip. Marcus has the cooling exhibit open.",
    marcus: "We can support your 100kW racks, but understand what you’re asking. The facility chilled water plant was sized for air-cooled densities. Direct-to-chip means CDUs, secondary loops, warmer water temperatures, all of it customer-driven. So the technology cooling loop downstream of our heat exchangers is your equipment, your risk, and your maintenance. We deliver chilled water to the wall of the hall at the design temperature. Past that wall, leaks, pumps, and thermal performance are Helios problems. That’s just where the physical demarcation sits.",
    options: [
      { text: "“Fine on ownership, but Ironvale installs and maintains it as a service, fully passed through to us at cost plus ten.”", grade: 1, feedback: "You solved the maintenance logistics and ignored the risk allocation, which was the actual point of his speech. Helios still owns thermal performance end-to-end, meaning every cooling failure in the hall is now definitionally a customer problem and the cooling SLA you fought for in the exhibit just stopped applying to the only cooling that touches your chips. Marcus conceded nothing that costs him anything." },
      { text: "“A demarcation is fine, every deal has one. But it sits at thermal outcomes, not at a wall. Ironvale commits to delivering the contracted heat rejection capacity, flow rate, and water temperature at the CDU connections, with the same SLA structure as the rest of the exhibit. Inside the racks is ours. And since your plant was, as you say, sized for air, we need the Exhibit C capacity numbers re-verified for the liquid load profile before RFS, by the commissioning agent.”", grade: 3, feedback: "Clean. You accepted the legitimate piece (rack-internal plumbing is customer scope at most colos), moved the demarcation to measurable delivery parameters (capacity, flow, temperature at the CDU), kept the SLA attached to them, and weaponized his own admission that the plant predates liquid cooling into a commissioning condition. Priya will love you for that last clause." },
      { text: "“Then we’ll just take more space and run everything air-cooled at 30kW per rack instead.”", grade: 0, feedback: "You redesigned your client’s deployment to dodge a contract issue. Tripling the footprint changes the economics of the entire deal (more racks, more cross-connects, more space charges, likely worse network topology for training workloads), and the technical premise is shaky anyway at modern GPU TDPs. Marcus just watched you negotiate against your own client." },
      { text: "“If the loop past the wall is all ours, then we expect a rent reduction, because we’re now self-supplying a service that was priced into the rate.”", grade: 2, feedback: "Economically literate, and repricing is a fair lever. But you accepted his risk allocation and are haggling over the price of a bad structure. The deeper problem stands: with the demarcation at the wall, no SLA covers the thermal path that actually touches your silicon, and a leak above your $40M GPU rows is legally orphaned. Price was never the main event here." }
    ],
    counter: "Accept a demarcation but move it from a wall to a set of measurable delivery parameters: heat rejection capacity, chilled water flow rate, and supply temperature at the CDU connections, with full SLA coverage on those parameters. Keep rack-internal plumbing as customer scope if needed. Then convert his “plant was sized for air” admission into an RFS condition: third-party re-verification of plant capacity against the actual liquid-cooled load profile."
  },
  bank: [
    { q: "From E1: why must the customer’s capacity grant be written in kW rather than kVA?", options: ["Because kVA is apparent power, and at an assumed power factor below 1.0 the same kVA number delivers less real power to the IT load", "Because utilities only bill in kW", "Because kVA cannot be measured at a PDU", "Because kW includes cooling load and kVA does not"], correct: 0, explain: "kW = kVA × power factor. 36 MVA at an assumed 0.9 PF is 32.4MW of real power, a ten percent haircut hidden in a unit. The deal belongs in kW at a defined downstream measurement point." },
    { q: "What is the difference between the ASHRAE recommended and allowable envelopes, and why does it matter in an SLA?", options: ["Recommended caps inlet temperature at 27°C while A1 allowable stretches to 32°C, so an SLA promising only “allowable” permits chronically hot operation", "Allowable is stricter than recommended, so operators prefer recommended", "Recommended applies to humidity only, allowable to temperature only", "The two envelopes are identical but published in different units"], correct: 0, explain: "Recommended is 18 to 27°C at the inlet, allowable A1 runs 15 to 32°C. Five degrees Celsius at the top end is the difference between healthy silicon and thermal throttling, and operators know which word they put in the draft." },
    { q: "Why does a 100kW-per-rack AI deployment break a legacy cooling exhibit?", options: ["Air cooling physically tops out around 20 to 40kW per rack, so the deal needs liquid cooling terms: delivery parameters, demarcation, and re-verified plant capacity", "Because 100kW racks are illegal under fire codes", "Because ASHRAE prohibits liquid in data halls", "It doesn’t, since cooling exhibits are density-neutral by convention"], correct: 0, explain: "Past roughly 40kW per rack, air can’t carry the heat regardless of containment quality. Rear-door exchangers, direct-to-chip, or immersion become mandatory, and every legacy term written for air (temperature SLAs, demarcations, density schedules) has to be renegotiated for the liquid path." }
  ],
  card: {
    term: "Rack Inlet Temperature",
    physical: "The air temperature actually entering the server, the only temperature the silicon experiences, governed by ASHRAE envelopes (18 to 27°C recommended, up to 32°C A1 allowable).",
    contractual: "The cooling SLA is only as good as its measurement point, and operators draft toward flattering proxies (hall averages, CRAH discharge) that can read compliant while the densest racks cook."
  }
}
];
